api/controllers/api_test.go, api/controllers/apps.go, api/controllers/apps_helpers_test.go, api/controllers/apps_test.go, api/controllers/helpers_test.go
add helpers that will let us set Headers b.c the `assert` helpers don't do that. we were going to need these helpers in the tests eventually
=> Fix api test failures

README.md
Basic edit to make sure that the link to cmd/crypt is pointing at the right place.
=> Fix link to cmd/crypt submodule

api/models/app.go
Update appname regex to match the one provided by AWS. Dashes are allowed, not underscores. Also updates the error message to explain in English. The regex is somewhat cryptic, but the rules are simple enough to explain in words.
=> Appname regex

api/controllers/routes.go, api/controllers/switch.go, client/switch.go, cmd/convox/login.go, cmd/convox/main.go, cmd/convox/switch.go
Changes behavior of `convox login` and `convox switch` to fit the usage we expect and to work with grid-like authentication proxies.
If you `convox login` then it will try auth on your system first and if that succeeds you're good. So you can exit a grid with `convox login <host>`.  
`convox swtich <hostname>` against a rack defaults to `convox login <hostname>`
`convox switch <rack name>` against a grid tries to switch you to a rack of the given name that you have access to in a grid. it suggests names if one does not match.
After login, the CLI does not know if it is talking to a Rack or the RackProxy
```
$ cx login grid.convox.com
Logged in successfully.
$ cx apps
APP      STATUS
compose  running
testy    running
$ cx switch prod
Switched to prod
$ cx apps
APP      STATUS
compose …
```
=> allow rack switching with grid API

api/models/manifest.go, api/models/manifest_test.go
Use random port assignment for the default externally mapped ports to avoid conflicts between apps
=> use random ports for defaults

api/models/app.go, api/models/formation.go, api/models/system.go
=> prevent scaling apps or racks into "stuck" situations

api/cmd/formation/handler/ecs.go, api/models/fixtures/web_external_internal.json, api/models/fixtures/web_postgis.json, api/models/fixtures/web_postgis_internal.json, api/models/fixtures/worker.json, api/models/helpers.go
CPU parameter is optional. Rather than tying directly to Memory which can cause ECS not to schedule the process for lack of available CPU units we simply don't specify it.
=> don't specify CPU parameter

cmd/convox/stdcli/stdcli.go
With this change you can now set a `.convox/app` config file in your project containing the app name of the deployment. This way, you no longer have to include the `--app` option and your deployment name can differ from the current directory name.
App name detection now goes in this order, with the first found being used:
- `--app`
- `.convox/app`
- current directory
Fixes #57
=> fetch app name from .convox/app file if it exists

cmd/convox/apps.go
Allow the passing of an app name as a positional arg to `convox apps info`. This is brings it into parity with the format of `convox apps create` and `convox apps delete` which should be less confusing.
```
$ convox apps info rails2
Name       rails2
Status     running
Release    RGBYRCRKWAP
Processes  db web
Hostname   rails2-1579255890.us-east-1.elb.amazonaws.com
Ports      web:5000
```
Backwards compatibility with the `--app <appname>` option as well as the directory name is maintained, but the positional argument, if present, gets priority.
```
$ convox apps info --app rails2
Name       rails2
Status     running
Release    RGBYRCRKWAP
Processes  db web
Hostname   rails2-1579255890.us-east-1.elb.amazonaws.com
Ports      web:5000
$ mkdir rails2
$ convox apps info
Name       rails2 …
```
=> Apps info args

api/manifest/manifest.go
will cause the port to be opened on the local docker host
=> support single port declaration in convox start

cmd/convox/run.go
=> convox run handles non-tty stdin

api/dist/kernel.json
simple first pass
- wait for resource signals, 15m timeout
- send signals after `cfn-init` completes
note: does not wait for ecs-agent or convox start to finish.
=> better rolling of asgs

cmd/convox/install.go
Redirection from https://docs.convox.com adds /docs/ to path, so removed the additional docs from the path so the URL wouldn't 404.
=> Documentation fix for #109

cmd/convox/builds.go
when `convox deploy` is creating the tarball, it now says "Creating tarball... OK".  then when it uploads the tarball it says "Uploading... OK".
should reduce confusion from folks on slow connections.
=> better deploy messaging

api/models/notify.go, client/notify_event.go
so we can consume anywhere we're already importing the client.
=> move notify event to client

api/models/templates/service/papertrail.tmpl
In conjunction with https://github.com/convox/papertrail/commit/48395b7899a7a2027b478679c49e68a23389d006
=> use a region specific bucket for papertrail lambda code

api/models/manifest.go
This prevents the doubling up of ContainerPorts when two external ports map to the same internal port. This prevents the ECS service from being deleted on every deploy because this list of container ports incoming (with dupes) mismatches the existing container ports (uniqued)
=> make the list of container ports unique

api/manifest/manifest.go
example shell session covering all the cases.
```
~/convox/demo (master*)$ cat docker-compose.yml
web:
build: .
command: bin/web
environment:
- DEVELOPMENT=true
- MESSAGE
ports:
- 80:3000
volumes:
- .:/go/src/github.com/convox/demo
~/convox/demo (master*)$ rm .env
~/convox/demo (master*)$ cx start
ERROR: env expected: MESSAGE
~/convox/demo (master*)$ echo "MESSAGE=foo" > .env
~/convox/demo (master*)$ cx start
RUNNING: docker build -t aythzffsrz /Users/csquared/convox/demo
...
~/convox/demo (master*)$ rm .env
~/convox/demo (master*)$ cx start
ERROR: env expected: MESSAGE
~/convox/demo (master*)$ # set it explicitly to empty
~/convox/demo (master*)$ sed -i '' 's/MESSAGE/MESSAGE=/' docker-compose.yml
~/convox/demo (master*)$ cx start
RUNNING: docker build -t fxontgmaxq …
```
=> Restore env var check on convox start

cmd/convox/start_test.go, test/exec.go
adds tests for blocking `convox start` until ENV is satisfied
=> tests for env var enforce on start

cmd/convox/env.go, cmd/convox/exec.go, cmd/convox/login.go, cmd/convox/logs.go, cmd/convox/releases.go, cmd/convox/run.go, cmd/convox/scale.go
```
$ cx apps info -a grid
Name       grid
Status     running
Release    RTUHBOURORW
Processes  web
Endpoints  grid-1749418666.us-east-1.elb.amazonaws.com:80 (web)
grid-1749418666.us-east-1.elb.amazonaws.com:443 (web)
```
=> use -a for app and standardize

api/cmd/formation/handler/ecs.go
Replace only if a new ELB is required, or if existing ELB port mapping is removed.
=> Refactor and fix ECSServiceReplacementRequired

cmd/convox/builds.go
If a `.dockerignore` file is present, use it to exclude files from the build tarball.
Fixes #135
=> exclude .dockerignore files from the build tarball

api/cmd/build/main.go, api/controllers/builds.go, api/manifest.yml, api/manifest/manifest.go, api/manifest/manifest_test.go, api/models/build.go, client/builds.go, cmd/convox/builds.go, cmd/convox/builds_test.go, cmd/convox/deploy.go, cmd/convox/start.go
This contains changes to the client and server which allow you to pass a `--file <filename>` option to `convox start`, `convox build`, and `convox deploy` if you want to use a file other than `docker-compose.yml`.  The option is never required and in all cases defaults to `docker-compose.yml`.
Fixes https://github.com/convox/kernel/issues/97
=> Specify docker-compose.yml file

api/dist/kernel.json, cmd/convox/install.go
This PR adds the ability to specify the size of the VPC you want to allocate for a convox rack. The subnets are calculated dynamically by splitting the chosen vpc into the 4 largest subnets that will fit.
=> Add vpc-cidr parameter to convox install for custom vpc sizes

api/controllers/instances_test.go, client/instances.go, cmd/convox/api.go, cmd/convox/instances.go, test/aws_cycles.go
```
$ convox instances
ID          IP             STATUS  PROCESSES  CPU    MEM
i-3963798e  54.85.115.31   active  0          0.00%  0.00%
i-01d2f1bf  54.84.251.187  active  0          0.00%  0.00%
i-c6a72b76  52.71.252.224  active  1          0.00%  19.16%
$ cx instances terminate i-01d2f1bf
Successfully sent terminate to instance "i-01d2f1bf"
$ cx instances
ID          IP             STATUS  PROCESSES  CPU    MEM
i-3963798e  54.85.115.31   active  0          0.00%  0.00%
i-c6a72b76  52.71.252.224  active  1          0.00%  19.16%
```
=> convox instances terminate

api/models/instances.go, client/instances.go, cmd/convox/instances.go
```
$ cx instances
ID          AGENT  STATUS  STARTED    PS  CPU    MEM
i-9e605020  off    active             0   0.00%  0.00%
i-22a4ea92  on     active  1 day ago  0   0.00%  0.00%
i-044777ba  on     active  1 day ago  0   0.00%  0.00%
i-5bf223ed  on     active  1 day ago  2   0.00%  31.93%
```
=> instance printing improvements

api/controllers/auth.go, api/controllers/routes.go, api/manifest.yml, client/auth.go, client/switch.go, cmd/convox/login.go, cmd/convox/login_test.go
* Add `/auth` func to client and call it if proxying to Rack `/apps` fails.
* Change `/switch` to not call `/system` (aka versionCheck). This works around Rack errors so users in a bad state to switch to a known good Rack.
This change enables users who can't log into Grid via the CLI because their current Rack is bad or nonexistent to get back to a good state. Once this is released they can:
1. `convox update`
2. `convox login grid.convox.com`
3. `convox switch [good rack]`
Depends on https://github.com/convox/grid/pull/107
=> log into Grid without a valid rack; switch to a valid rack

api/dist/kernel.json
use:
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
not:
=> us the ami ids from the ECS docs, not the aws marketplace

api/controllers/services.go, api/models/service-datastore.go, api/models/service-papertrail.go, api/models/service-webhook.go, api/models/service.go, api/models/services_test.go, client/services.go, cmd/convox/services.go, cmd/convox/stdcli/stdcli.go, cmd/convox/stdcli/stdcli_test.go
- parses any cli option passed to service create
- passes options through to CF template
- reports errors from CF so we don't need to validate presence, etc in models
- adds status reason to service model
- abstracts service creation to hopefully make definition, addition easier
- changes "URL" return to "exports" key/value pairs for future compatibility
- fixes service tagging as well
=> Service Options (was RDS options)

api/models/helpers.go
In at least a few callsites generateId is used for generating a password, which really should be done from crypto/rand
=> Fixes #234 -- use crypto/rand in generateId instead of math/rand

api/dist/kernel.json
This isn't an integration with ECR, it simply allows ECS to pull images from ECR. This is important for continuous integration of a local convox build chain (we deploy automated convox builds to ECR so CloudFormation is able to boot them).
This change allows ECR to be used with `convox/api` and `convox/registry` images.
=> Include ecr:GetAuthorizationToken permission

Dockerfile, api/models/ssl.go
Automatic intermediate cert chain generation was causing problems with the `convox ssl create` command for:
* Manually-created self-signed certs
* Self signed-certs created with the `--self-signed` option
* Any other cert with the full chain already bundled
The fixes for these were:
* Detect if the cert is self-signed, and if so, don't try to complete the chain and don't upload a chain to AWS
* For non-self-signed, strip away everything except the end-entity cert and then regenerate the chain
=> SSL chain fix

ci/dependencies-pre.sh, ci/test-cleanup.sh, circle.yml, cmd/convox/install.go
* Retry CF Delete Stack to work around known VPC DELETE_FAILED problem
* Print generic uninstall progress message every 2m to address log CF wait periods and CircleCI timeouts
* Upgrade awscli
* Use `aws` to delete S3 buckets, Log Groups, and Registries after test
This builds on top of https://github.com/convox/rack/pull/280
* Split out deleting apps to it's own step
* Split out post-uninstall cleanup into it's own step
* Spin until CF stack updates finish
* Spin until app ELB is avilable
And https://github.com/convox/rack/pull/281
* Tweak CF DependsOn to try to fix GatewayAttachment DELETE_FAILED
The GatewayAttachment DELETE_FAILED still happens occasionally, which means a CI test may take up to 50 minutes. I have opened up a support ticket to further root cause this problem.
=> CI Stability

api/manifest/manifest.go, api/models/release.go
moves linking on `convox start` to multiple, isolated methods
ensures first port wins in multiple port declarations (instead of error)
=> refactor links

api/manifest/manifest.go, api/manifest/manifest_test.go, api/models/fixtures/web_redis.json, api/models/fixtures/web_redis.yml, api/models/release.go
adds env vars for links that fit a URL scheme. for a link named `redis` this will expose:
- `REDIS_URL`
- `REDIS_SCHEME`
- `REDIS_HOST`
- `REDIS_PORT`
- `REDIS_PATH`
- `REDIS_USERNAME`
- `REDIS_PASSWORD`
```bash
$ docker exec -it 57025814486e env | grep REDIS
REDIS_HOST=172.17.0.1
REDIS_PASSWORD=password
REDIS_PATH=/0
REDIS_PORT=6379
REDIS_SCHEME=redis
REDIS_URL=redis://:password@172.17.0.1:6379/0
REDIS_USERNAME=
```
=> More link vars

api/models/templates/service/mysql.tmpl, api/models/templates/service/postgres.tmpl
not sure what else is required to expose the MultiAZ parameter to `convox service create`
Seems like support for this param is already there in api.go
=> add support for MultiAZ parameter in the db CF templates

api/dist/kernel.json
* Use `/dev/xvdcz` to mount the Docker directory and use 50GB for the default size
* Don't let the instance count drop below desired count
=> Change docker volume location and instance rolls

api/cmd/build/main.go, api/helpers/helpers.go, api/manifest/manifest.go, api/models/build.go, api/models/docker.go, api/models/release.go, api/models/release_test.go, api/models/system.go, ci/tests/example-app
Centralize both v1 and ECR login into a single AppDockerLogin method.
The build API auths before shelling out to `cmd/build -push` utility.
The release API auths before introspecting images for LINK vars.
The cmd/build and api/manifest packages no longer care about auth. These were extracted to share with `convox start` who doesn't care about auth.
=> Refactor Registry Login

api/models/service.go
The `u` user is unnecessary to connect to elasticache.
=> Remove u@ from redis url

api/controllers/routes.go, api/controllers/system.go, api/models/system.go, client/system.go, cmd/convox/rack.go, cmd/convox/rack_test.go
This is one step towards an automated `convox rack rollback` procedure: storing the rack version history. Update to this, and the next and future updates will be stored in dynamodb.
* On system version update, save new version in the releases table for the RACK app
* SystemReleaseList endpoint
* `convox rack releases` prints a table of current and historical saved releases
* `convox rack releases` prints the next release if available
=> Save Rack versions in the Releases table

api/cmd/formation/handler/ec2.go, api/cmd/formation/handler/formation.go
* Custom handler for EC2 NAT Gateway
Tested working by adding this to kernel.json:
```json
"EIP": {
"Type": "AWS::EC2::EIP",
"Properties": {
"Domain": "vpc"
}
},
"NatGateway": {
"Type": "Custom::EC2NatGateway",
"Properties": {
"ServiceToken": { "Fn::GetAtt": [ "CustomTopic", "Arn" ] },
"AllocationId": { "Fn::GetAtt": [ "EIP", "AllocationId" ] },
"SubnetId": { "Ref": "Subnet0" }
}
},
```
TODO:
=> NAT Gateway

api/dist/kernel.json
I observed instances failing to start new tasks due to a full root partition. The ECS tasks had this error:
> CannotPullContainerError: Error: image myapp-pwslydfenh:web.BHGHDJOBYMU not found
`docker info` showed that the Docker volume was fine, but `df` showed that the root partition was 100% full, with `du` indicating /var/lib/docker/containers was using a lot of disk for log storage
```
[root@ip-10-0-3-4 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  7.8G     0 100% /
devtmpfs        7.9G   88K  7.9G   1% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
[root@ip-10-0-3-4 /]# du -d4 -h * | sort -hdf
...
230M	var/cache
429M	usr
1.1G	var/lib/docker/containers/e95be0c289d8194c291e3ddb4c91f9028fa50361aa03695ea48bee00900bcc19
1.2G	var/lib
1.2G …
```
=> Cap Docker Logs

api/dist/kernel.json
Maybe there is a reason for this I'm missing, but as-is, I can't use the `DockerImageApi` param to test new convox api builds (by pointing it at my own ECR repos). This makes it hard to quickly switch a rack between builds for testing.
Side-note, why does this param have a `Development` condition? How does that come into play exactly?
=> Respect DockerImageApi parameter in ECS definitions

.travis.yml, README.md
Coveralls has been down a lot. We also are not getting any value out of coverage analysis in general. Remove for now.
=> remove coveralls and special travis config in favor of `make test`

api/models/service.go
As discussed, this is simply a followup to #341 that adds `Service.IsBound` similar to `App.IsBound`.
=> Introduce Service.IsBound

api/controllers/processes_test.go, api/models/models.go, api/models/process.go, test/aws_cycles.go
Addresses this error which happens frequently on bigger apps:
```
$ convox ps
ERROR: ThrottlingException: Rate exceeded
status code: 400, request id: 155f75b2-dac8-11e5-8038-cb0464aa31e7
```
* Increase ECS client retries to better deal with throttling
* Describe ECS instances only once
* Describe EC2 instances only once
This results in less requests total, and more time to backoff/retry if throttled.
=> PS Throttle

cmd/convox/env.go
=> add a helpful error message when trying to set vars with `convox env`

api/dist/kernel.json
* Use agent 0.66 (PR: https://github.com/convox/agent/pull/18)
* Add InstanceBootCommand Parameter
* Add set -e to UserData to guard against failures in InstanceBootCommand or anything else really
The new parameter opens up a new ability to configure individual racks differently. I want this to do agent experiments on a specific rack that is having problems at production scale. 
I.e. `InstanceBootCommand='curl -s https://convox.s3.amazonaws.com/agent/0.66-experimental/convox.conf > /etc/init/convox.conf ; restart convox'`
This also opens up lots of possibilities to configure a logging container on every instance, install extra packages, etc. See: https://github.com/convox/rack/issues/356
=> Agent Flags via InstanceBootCommand parameter

cmd/convox/install.go
Taking over from https://github.com/convox/rack/pull/404 CC @mwarkentin.
Adds a stylistic change on top of the patch to keep `convox install --help` output static.
=> Mwarkentin 161 rack password

api/controllers/proxy.go, api/controllers/routes.go, client/proxy.go, cmd/convox/proxy.go
Adds a `convox proxy` command to make it easier to connect to services running isolated inside a Rack.
`convox proxy 5432:my-postgres.rds.amazon.org:5432`
=> convox proxy

api/dist/kernel.json
Followup to https://github.com/convox/rack/pull/512, releasing with https://github.com/convox/rack/pull/509
=> amzn-ami-2016.03.a-amazon-ecs-optimized

api/cmd/formation/handler/ec2.go
Updates in us-west-2 were failing because of:
```
UPDATE_IN_PROGRESS	Custom::EC2AvailabilityZones	AvailabilityZones
UPDATE_COMPLETE	Custom::EC2AvailabilityZones	AvailabilityZones	
UPDATE_FAILED	AWS::EC2::Subnet	Subnet1
CustomResource attribute error: Vendor response doesn't contain AvailabilityZone1 key in object arn:aws:cloudformation:us-west-2:132866487567:stack/west/9def75e0-f5da-11e5-95b7-50d5ca2e7cd2|AvailabilityZones|727035d2-aa3d-457c-80bc-2987a3eb9e46 in S3 bucket cloudformation-custom-resource-storage-uswest2
```
It's not clear why `Custom::EC2AvailabilityZones` is getting updated, as this isn't happening in us-east-1 and doesn't make sense. 
However, it is clear that the EC2AvailabilityZones update handler was not returning any data, where the AWS::EC2::Subnet resource is …
=> Custom::EC2AvailabilityZones Bugfix

api/cmd/formation/handler/ec2.go
Similar to https://github.com/convox/rack/pull/524, I observed CloudFormation errors updating the Custom::EC2NatGateway:
```
18:35:13 UTC-0700	UPDATE_ROLLBACK_FAILED	AWS::CloudFormation::Stack	convox	The following resource(s) failed to update: [NatGateway2, NatGateway1].
18:35:11 UTC-0700	UPDATE_FAILED	Custom::EC2NatGateway	NatGateway1	Failed to update resource. could not update
18:35:10 UTC-0700	UPDATE_FAILED	Custom::EC2NatGateway	NatGateway2	Failed to update resource. could not update
```
=> Custom::EC2NatGateway update doesnt error

cmd/convox/run.go
When `convox run` is run outside of a TTY it is currently returning this error:
ERROR: operation not supported by device
=> don't try to get terminal size when not a tty

.travis.yml, circle.yml
Update to Go 1.6.1 release: https://groups.google.com/forum/#!topic/golang-nuts/9eqIHqaWvck
* This follows up #539. 
* It appears that 1.6-alpine will pick up 1.6.1 without explicitly specifying it (and presumably later point releases as well). 
* Once gimme supports it, it may make sense to use `stable` for the latest stable version on Travis CI (see https://github.com/travis-ci/gimme/issues/39)
=> update CI to Go 1.6.1

api/manifest/manifest.go, api/models/release.go
- Call `mapping.Balancer` to get the port, rather than `mapping.Container`
- Drop the "com." from the labels. The format is now:
```
labels:
- "convox.port.80.protocol=proxy"
```
using the string format or:
```
labels:
convox.port.80.protocol: "proxy"
```
using the map format.
Fixes #542
=> ProxyProtocol fix

ci/cleanup.sh, ci/install.sh, ci/report.sh, ci/uninstall.sh
Quick fix for CI error. Install from template in S3 like everyone else.
```
'...' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
status code: 400, request id: 72837ebe-033c-11e6-8678-5b203d139953
ci/install.sh returned exit code 1
```
=> install from template in S3 assuming VERSION build parameter is set

api/dist/kernel.json, api/provider/aws/certificates.go, cmd/convox/proxy.go, cmd/convox/services.go
Taking over for #550. Phew!
As a recap, the goal was to get the latest AMIs.
Changes on the new Amazon Linux broke the old userdata around doing a `docker restart` to pick up some different settings. Going forward we want to write docker settings to the disk earlier in the boot process so they are there when the AMI does the first `docker start`.
CloudInit and its bootcmd hook run earlier in the boot process, but it took us a while to learn how to use this without causing other side effects. Namely it seems impossible for our UserData supplied bootcmd to not prevent the ECS bootcmd that's baked into the AMI from executing. Thats a very important command for initializing Docker storage settings.
The workaround for now is to copy the ECS bootcmd into our userdata. We will have to be careful …
=> amzn-ami-2016.03.a-amazon-ecs-optimized + cloud-init

api/models/environment.go
Solves #335 by not getting the env settings if app status is creating.
=> Block environment get while creating

cmd/convox/run.go
When executing a `convox run` command, make sure the process ID is a
valid one.
I could see this exact logic implemented in `client/process.go` but this being my original method, I went with it.
Should solve #601
=> Validate the process ID passed to run

api/manifest/manifest.go
Log `io.Copy` errors.
Set `O_WRONLY` mode when we open the file to write a download. Without this we get a "bad file descriptor" error and the written file is empty.
=> use O_WRONLY mode, print copy errors

api/dist/kernel.json
@MiguelMoll and I have been tracking down an error in CI with `convox run`:
```bash
$ convox run --app httpd-807 web echo "hello world”
> hello world
> ERROR: API error (500): Container c5ef6ea6901a616ec68f57712b2eb41104b654949ef30d72b625e473f80f1a23 is not running
```
The root cause was that Docker 1.11 was getting onto newly installed Racks from a `yum update`. This patch prevents automatically updating all packages like Docker, favoring getting Docker updates from new AMIs.
=> dont upgrade all packages; fixes a surprise update to docker 1.11

Development.md
When PR #716 was merged, racks running locally were not able to SSH into the instances. With this change, any future modifications will be handled for local racks.
Figured opening all ports (0 - 65535) for the "My IP" source will help in the future. Thoughts?
=> Clarify AWS security groups for local rack development

api/controllers/formation.go
In https://github.com/convox/rack/commit/10605762873a69239b0184e9093d6cc08a3a6a66 an API change was introduced where sending `count=-1` to the `convox scale` API is valid and indicates to delete the process type and ELB.
This was released in [rack 20160602143119](https://github.com/convox/rack/releases/tag/20160602143119) and [CLI 20160602213113](https://dl.equinox.io/convox/convox/stable/archive).
There have been reports of an serious side effect. Doing a `convox scale --memory=512` on older clients sends a `count=-1` value as a default, triggering the new deletion behavior.
This API update asserts a minimum client version before accepting `count=-1`.
=> Critical Fix: Older clients can accidentally delete a process / ELB

Dockerfile
Version `golang:1.6-alpine` will pull the latest release of 1.6.x along with an updated version of alpine. This in turn updates docker to 1.11.1 which can break compatibility with ECS.
=> Pin to use golang:1.6.1-alpine

api/models/process.go
Following changes are to make `convox ps` act a bit more reliable when encountering errors while gathering data. The goal is to log errors (if any) and fail gracefully.
=> Improving `convox ps` reliability

cmd/convox/login.go
Small tweak that should fix #709. The usage prompt states that a Console API key is also accepted.
=> Add some clarity to what the login password can accept

cmd/convox/exec.go
Allows `convox exec` to function even when stdin is not a TTY.
=> only attempt terminal manipulation on tty stdin

api/cmd/build/README.md, api/cmd/build/main.go
The `.netrc` file lives inside a container to help authorize private git repos.
Also made switch to logging a warning if `git submodule` fails instead of bailing on a build.
Fixes #771
Fixes #833
=> Use .netrc for build credentials

api/controllers/instances.go, api/controllers/processes.go, api/dist/kernel.json, api/models/app.go, api/models/instances.go, api/models/process.go, cmd/convox/logs.go, cmd/convox/ps.go, cmd/convox/rack.go, manifest/build.go, manifest/build_test.go, manifest/fixtures/interpolate-env-var.yml, manifest/fixtures/repeat-image.yml, manifest/fixtures/shift.yml, manifest/manifest.go, manifest/manifest_test.go, manifest/service.go
- closes #1009 docker-compose variable substitution [@awsmsrc]
- closes #1023 restore convox.start.shift label for per-service shift [@ddollar]
- closes #1026 Kernel changes to lockdown rack install permissions [@MiguelMoll]
- closes #1028 adds `convox rack ps` and `convox rack logs` [@ddollar]
- closes #1031 Fix proxy parameters [@bladealslayer]
- closes #1032 Add a timeout for retrieving process stats [@MiguelMoll]
- closes #1041 Handle manifests with repeated images [@mattmanning]
=> [RELEASE] 20160811

cmd/convox/install.go
The --region flag already checks AWS_REGION for a value. Checking the env variable directly will override the --region value.
=> Remove the check/set for AWS_REGION

cmd/convox/builds.go, cmd/convox/stdcli/stdcli.go
`stat.Mode() & os.ModeCharDevice) == 0` means data is being piped to stdin, otherwise stdin is from a terminal.
=> Fix logic for IsTerminal()

cmd/convox/rack.go, provider/aws/dist/rack.json, provider/aws/processes.go, provider/aws/processes_test.go
- closes #1281 require at least 2 api tasks in service [@ddollar]
- closes #1283 don’t show error on empty process list [@ddollar]
- closes #1284 allow specifying a rack update beyond latest published [@ddollar]
=> [RELEASE] 20160930

api/cmd/build/main.go, cmd/convox/start.go, manifest/build.go, manifest/build_test.go, manifest/fixtures/specific-service.yml, manifest/manifest.go, manifest/push.go, manifest/run.go
This patch provides support for specifying a specific service to start within an application and additionally/optionally a particular command to run in the following format
```
convox start
convox start api
convox start api rake db:migrate
```
The main motivation is for one off tasks such as migrations and data seeding tasks.
It was decide to add these to start as opposed to adding something like a --local flag to run as in the future we may want a "local" rack "provider" and I didn't want to pollute the run namespace/command/api
=> Optionally specify a service and or command with convox start 

client/auth.go, cmd/convox/login.go, cmd/convox/login_test.go
Copy change to the login error message. Links to a redirect that's in https://github.com/convox/site/pull/320
```
$ convox login
Password: 
ERROR: invalid login. Create an account at https://convox.com/signup
```
=> invalid login links to signup

cmd/convox/doctor.go
This check encourages users to declare the environment variables
that correspond to links in the `environment:` section of their
docker-compose.yml. This explicitness is not yet supported by
`convox start`.
=> Remove link env var check from doctor

api/manifest.yml, api/workers/autoscale.go, bin/checklinks.sh, manifest/fixtures/invalid-health-check.yml, manifest/fixtures/shift-with-ssl.yml, manifest/labels.go, manifest/manifest.go, manifest/manifest_test.go, manifest/ports_test.go
- closes #1475 Use console.convox.com instead of docker.local as host in swagger manifest [@soulshake]
- closes #1476 validate convox.health.port [@ddollar]
- closes #1478 When shifting ports, also shift 'convox.port.xxx.protocol'. [@soulshake]
- closes #1479 Add a tiny shell script in bin/ to check DocsLink URLs. [@soulshake]
- closes #1480 autoscale even when converging [@ddollar]
=> [RELEASE] 20161215

provider/aws/dist/rack.json
As a result of #1063, `convox ps stop` was broken due to missing permissions for `ecs:StopTask`. This PR simply adds it.
I haven't checked for any other missing permissions, I just happened to stumble onto this one during some debugging.
=> Fix `convox ps stop`

.travis.yml, api/controllers/racks.go, api/controllers/switch.go, ci/set-client-id.sh, provider/aws/dist/rack.json, provider/aws/resource.go
- closes #1623 update AMIs [@mattmanning]
- closes #1625 'only available on console' -> 'only available when logged into console.convox.com' [@soulshake]
- closes #1627 set ci client-id on travis [@nzoschke]
- closes #1629 populate Type from Service tag if Resource tag is empty [@mattmanning]
- closes #1631 use DesiredCount 2 for rack web service [@mattmanning]
- closes #1633 fix race condition with --private installs (redux) [@mattmanning]
=> [RELEASE] 20170130

provider/aws/dist/rack.json
Tested this again (after closing https://github.com/convox/rack/pull/1934) and it seems to be working fine (I was testing with a local Rack instead of uploading rack.json to CF web interface; maybe that was the problem?).
Tested manually with:
```
Ami	
ApiCpu	128
ApiMemory	128
Autoscale	Yes
BuildCpu	0
BuildImage	
BuildInstance	
BuildMemory	1024
ClientId	dev@convox.com
ContainerDisk	10
* CustomTopicRuntime	nodejs4.3
Development	No
Encryption	Yes
ExistingVpc	
InstanceBootCommand	
InstanceCount	3
InstanceRunCommand	
* InstanceType	m4.large
InstanceUpdateBatchSize	1
Internal	No
InternetGateway	
Key	
* Password	****
Private	No
PrivateApi	No
Subnet0CIDR	10.0.1.0/24
Subnet1CIDR	10.0.2.0/24
Subnet2CIDR	10.0.3.0/24
SubnetPrivate0CIDR	10.0.4.0/24
SubnetPrivate1CIDR	10.0.5.0/24
SubnetPrivate2CIDR …
```
=> Make instance tenancy refer to Tenancy instead of being hardcoded to default

provider/aws/dist/rack.json
Follow up to https://github.com/convox/rack/pull/1963 after shipping the needed permissions in a required release (https://github.com/convox/rack/releases/tag/20170306140228)
Addresses #1933
=> Allow dedicated installs by using Tenancy param instead of hard coding "default"

api/models/helpers.go, api/workers/events.go, provider/aws/dist/rack.json
Fixes an issue with the sqs policy. Also fix the stack name when looking for a log group of a rack or app. With a rack name `staging`, it would look for a stack named `staging-staging`.
=> policy permission fix and rack log group

cmd/convox/install.go, cmd/convox/install_test.go, cmd/convox/main_test.go, provider/aws/dist/rack.json
- closes #2258 convox cli install tests [@MiguelMoll]
- closes #2259 Default to 200GB disk instead of 50GB disk on dedicated build instances [@mattmanning]
=> [RELEASE] 20170721

cmd/convox/install.go, provider/aws/dist/rack.json
Previously, updating `InstanceCount` on a rack with a `SpotInstanceBid` price would:
- Update the on-demand ASG desired capacity to `InstanceCount`
- Which triggers starting many new on-demand instances
- Which waits for many SUCCESS signals
- Then waits for the spot instance worker to reduce the on-demand ASG back to the proper amount
This resulted in long stack updates and windows of unneeded capacity when spot instances are available.
With this change, when spot is enabled, updating `InstanceCount` makes no changes to the on-demand ASG, so the stack update should be very quick, and the spot instance worker will re-balance in the background.
=> Spot count desired capacity

provider/aws/dist/rack.json
Turning on spot instances on a rack with #2291 results in a CF error:
> 22:16:06 UTC-0700    UPDATE_FAILED    AWS::AutoScaling::AutoScalingGroup    Instances    MinInstancesInService must be less than the autoscaling group's MaxSize
Returning to a hard-coded large ASG MaxSize should avoid this
=> hard code ASG max size

.dockerignore, api/controllers/processes.go, api/controllers/system.go, client/processes.go, cmd/convox/run.go, provider/aws/formation/rack.json, provider/aws/processes.go, structs/process.go
- closes #2522 do not attempt to encrypt root volume as it is incompatible with ecs ami [@ddollar]
- closes #2523 optionally specify timeout for attached runs [@ddollar]
- closes #2524 autoscale should not block a type-only rack scale change [@ddollar]
=> [RELEASE] 20180307

provider/aws/aws.go, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json
- closes #2512 Added possibility to specify multiple Security Groups in gen1 [@radekl]
- closes #2584 Increase MaxRetries for AWS clients from 3 to 7 [@thieman]
- closes #2585 Added support for multiple security groups for rack router [@radekl]
=> [RELEASE] 20180405

provider/aws/lambda/autoscale/handler.go, provider/aws/workers_cleanup.go
- closes #2716 fix bug in chunker when it falls on an exact boundary [@ddollar]
=> [RELEASE] 20180604

provider/aws/formation/resource/redis.json.tmpl
i noticed this just now when i was about to deploy and got this error:
```
ERROR: json syntax error: line 75 pos 6: invalid character '}' looking for beginning of object key string:       }
```
=> fix invalid json in redis resource template

provider/aws/formation/rack.json, provider/aws/helpers.go, provider/aws/processes_test.go, provider/aws/workers_spotreplace.go
- closes #2957 fix for convox exec in awsvpc mode [@ddollar]
- closes #2959 on demand calculator uses actual running spot count [@ddollar]
=> [RELEASE] 20180927

pkg/cli/builds.go, pkg/cli/cli.go, pkg/cli/deploy.go, pkg/cli/fixtures_test.go, pkg/cli/test.go, pkg/cli/test_test.go, provider/aws/formation/resource/postgres.json.tmpl, provider/local/process_unix.go, provider/local/system_linux.go
- closes #2974 escape command args in systemd [@ddollar]
- closes #2976 add `convox test` for testing apps on a rack [@ddollar]
- closes #2977 use correct postgres 10 parameter group format [@ddollar]
=> [RELEASE] 20181010

pkg/cli/resources.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/service.go, pkg/manifest/testdata/full.yml, provider/aws/formation/service.json.tmpl, provider/aws/helpers.go, provider/aws/resource.go, provider/aws/template.go, provider/aws/workers_events.go
- closes #3018 fix cli help for resources proxy [@ddollar]
- closes #3019 enable system volume for ecs-optimized amazon linux 2. [@ffjia]
- closes #3020 fall back to rack log group for stack logs [@ddollar]
- closes #3021 make draining timeout configurable for gen2 [@ddollar]
=> [RELEASE] 20181115

README.md
The README has a link to open a new issue in this repository, but it has issues disabled.
=> README: remove issue link

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/params.go, pkg/manifest/testdata/full.yml, provider/aws/releases.go
Allows setting parameter overrides inside `convox.yml`
```
params:
RedirectHttps: no
services:
web:
build: .
port: 3000
```
**Note: Parameters specified in this way will be applied during every release promotion, potentially changing any values you have set manually with `convox apps params set`**
=> read parameters overrides from convox.yml

Gopkg.lock, pkg/router/http.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl, vendor/github.com/convox/stdapi/server.go
- closes #3272 propagate ecs service tags to tasks [@ddollar]
- closes #3273 use default http transport for local rack router [@ddollar]
- closes #3274 update convox/stdapi to force tls 1.2 support [@ddollar]
=> [RELEASE] 20190628

provider/aws/processes.go, provider/kaws/system.go
- closes #3293 allow kaws rack update to proceed when stack update is noop [@ddollar]
- closes #3295 dedupe tasks to work around bug in ECS:ListTasks [@ddollar]
=> [RELEASE] 20190813

provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/templates/resource/webhook.tmpl, provider/kaws/formation/rack.yml
- closes #3322 revert inline lambda to nodejs 8.10 until cloudformation supports 10.x [@ddollar]
=> [RELEASE] 20191023

pkg/api/instance_test.go, pkg/api/process_test.go
This picks up three dropped error variables in the `pkg/api` tests.
=> api: fix dropped test errors

provider/aws/releases.go
- closes #3415 Keep any existing custom app tags that should supersede the Rack tags [@beastawakens]
=> [RELEASE] 20201109

pkg/cli/rack.go, provider/aws/formation/rack.json
This adds a new formation parameter named `HighAvailability`. it's `true` by default and setting it to `false` will reduce the number of subnets/auto-scaling replicas and a few other resources.
=> Add support to enable/disable High Availability when creating racks

cmd/convox/Makefile, go.mod, go.sum, vendor/modules.txt
Tidy up go modules and install `xgo` without modifying `go.mod` to avoid `inconsistent vendoring` errors when building the cli.
Edit: build was  successfully created https://github.com/convox/rack/releases/tag/20211124183359-fix-build
=> Fix inconsistent vendoring error when building the cli

pkg/cli/rack.go, provider/aws/formation/rack.json, provider/aws/helpers.go
User can pass a CRON with ScheduledActionDownCron and ScheduledActionUpCron to set the Schedule Action
Example:
To shutdown the cluster on Friday 6pm (UTC) until Monday 9am (UTC)
```
convox rack install aws -n v2  ScheduleRackScaleDown="0 18 * * 5" ScheduleRackScaleUp="0 9 * * 1"
```
Or update the schedule:
```
convox rack params set ScheduleRackScaleDown="0 18 * * 5" ScheduleRackScaleUp="0 9 * * 1"
```
=> User can set a schedule to shut down and up the cluster

ci/test.sh
Fix a ci test step. When buildkit is enabled the logs are displayed slightly differently.
=> Fix ci test step

pkg/cli/apps.go, pkg/cli/apps_test.go
When using `convox apps cancel` we were not injecting the environment variables properly
=> Fix environment variable bug when using convox apps cancel

pkg/helpers/aws.go
Sometimes the request has a slight difference from the expected startTime. Possibly because when dividing, it would round up to the closest number.
The difference in the request caused it to fail intermittently. The error was happening a lot.
https://app.circleci.com/pipelines/github/convox/rack/4125/workflows/faa681cf-9cbe-4887-9ffa-15c68f14218a/jobs/9824
_I didn't want to include this commit into #3570 because the e2e was running and committing this would restart it._
=> Use MicroSecond instead of Millisecond

.circleci/config.yml
Only enables unit tests for forked PRs. _Pass secrets to builds from forked pull requests_ is not enabled.
=> Enable the unit tests for forked PRs

.circleci/config.yml
We don't expose env vars for forked PRs, so we won't run the release process on them. 
The `ci` job will not run on forked PRs. The `test` job will always run.
=> Ignore release test for forked PRs

provider/aws/formation/rack.json
- closes #3628 Private subnets should only be created when rack is Private [@Twsouza]
- closes #3629 feat-829: Add support to restrict rack api access from certain ips [@nightfury1204]
=> [RELEASE] 20230119

provider/aws/formation/rack.json
- closes #3633 Use same redis version for rack resource and app resource [@Twsouza]
- closes #3634 Create build instance policy parameter [@Twsouza]
- closes #3641 Support ECS clusters based on X2gd instances [@kyleroot]
=> [RELEASE] 20230207

pkg/cli/fixtures_test.go, pkg/cli/resources.go, pkg/cli/resources_test.go, provider/aws/formation/rack.json, provider/aws/formation/timer.json.tmpl, provider/aws/workers_heartbeat.go
- closes #3657 Migrate to launch template [@Twsouza]
- closes #3661 Set privileged option on container definition when is set on service [@Twsouza]
- closes #3662 Autoscale extra for non-ha racks [@Twsouza]
- closes #3674 Prepend the url scheme only if the resource doesn't have one [@Twsouza]
- closes #3677 Add on_demand and spot instance count for telemetry [@nightfury1204]
=> [RELEASE] 20230516

provider/aws/formation/rack.json
AWS changed the behavior for existing for VPC Gateway attachment, even previous versions are not working anymore (I couldn't find any notes on that, I came at this conclusion by testing old releases)
No.
Create a first rack (it can be the default settings), then try to install using the same VPC and IG, see https://docsv2.convox.com/reference/vpc-configurations#installing-into-an-existing-vpc
=> Remove ExistingGatewayAttachment on installing into existing VPC

provider/aws/formation/rack.json
BuildLaunchTemplate will only be created if the rack has dedicated builder set. Add DedicatedBuilder condition to BuildLaunchTemplate.
No, it's a fix
- Install a new rack with the latest release with `BuildInstance` as empty.
- Try to update the rack to this RC (to be created).
=> Add DedicatedBuilder condition to BuildLaunchTemplate

provider/aws/formation/rack.json
This will add logging configuration to build task definitions. Not having logging configuration is flagged by aws security scan. So adding this as best practices.
=> Add log configuration build task

provider/aws/processes.go
Added all resource specific env variables to the service created in convox run command. 
Now these variables are added automatically in the ECS Task definition for the service - 
X_URL=
X_USER=
X_PASS=
X_HOST=
X_PORT=
X_NAME=
where X is one of the resource types.
=> added resource env variables in service for convox run command - fix/convox-run-resource-env-vars

provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json
Gen-1 apps have a param - "TaskRole" to attach a IAM role to the ECS Task running the container. Currently due to insufficient permissions to assign IAM roles, the cloudformation stack isn't able to attach the IAM role with permissions to the task definition. This fix attaches the necessary policy of 'iam:PassRole' to the IAM role attached to CloudFormation stack.
=> Adding policy to cloudformation stack role of GEN-1 app

provider/aws/formation/rack.json
Added a Rack Parameter - `EcsContainerStopTimeout` for configuring the default timeout after which the container is forcibly stopped be sending a SIGTERM signal.
=> added rack param ecs_container_stop_timeout

provider/aws/processes.go
Added a fix for convox run to support the policies added to service.
=> convox run supports policies added to service

pkg/helpers/tar.go
Added fix for `convox cp` command for resolving the issue of copying files from remote to local filesystem.
=> fix for copy command - from remote to local 

provider/aws/formation/rack.json
Fix for updating the default value for the rack param EcsContainerStopTimeout.
=> Update on Default value for rack Param EcsContainerStopTimeout

pkg/helpers/tar.go, provider/aws/formation/rack.json
=> 20241111184017

pkg/manifest/service.go, provider/aws/lambda/autoscale/handler.go, provider/aws/workers_spotreplace.go
- Fix env to support '=' sign to be included in the env value
- Remove sensitive information from autoscale handler
- Fix spot replace when instance is in rollback state
=> Fix spot replace, env value with '=' and remove sensitive information autoscaling logs

pkg/manifest/resource.go, pkg/manifest/service.go, provider/aws/formation/resource/efs.json.tmpl, provider/aws/formation/resource/mariadb.json.tmpl, provider/aws/formation/resource/memcached.json.tmpl, provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/formation/resource/redis.json.tmpl, provider/aws/releases.go, provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/postgres.tmpl, provider/aws/templates/resource/redis.tmpl, provider/kaws/template/resource/mysql.yml.tmpl, provider/kaws/template/resource/postgres.yml.tmpl
Introduces optional tags fields to unify resource metadata Enables consistent tagging for improved environment management
New feature.
Add tags in the convox.yml to the resource you want to add:
```yml
resources:
mydb:
type: postgres
options:
storage: 100
tags:
myresourcetag1: resourcetag1
myresourcetag2: resourcetag2
```
=> Adds resource tagging

.gitignore, provider/aws/formation/rack.json, provider/aws/lambda/autoscale/Makefile, provider/aws/lambda/formation/Makefile, provider/aws/lambda/lifecycle/Makefile, provider/aws/lambda/syslog/Makefile, provider/aws/templates/resource/syslog.tmpl
Ensures a fully self-contained AWS Lambda deployment and reduces runtime dependencies
Change the autoscaler to build a fully statically linked binary
=> Enables fully statically linked binary

Makefile, cmd/build/Dockerfile.arm, provider/aws/formation/rack.json
Enables ARM64 builds with dynamic image selection to enhance compatibility and streamline deployment workflows
No, fix builds for arm64 racks
Install the latest release and deploy an application.
=> Adds multi-arch build support
