convox/rack

cmd/convox/install.go
Fix https://github.com/convox/cli/issues/86
=> Add support for AWS STS session tokens when installing convox

cmd/convox/services.go
makes services create consistent with the rest of the commands
=> dont wait for services to create

cmd/convox/api.go, cmd/convox/api_test.go
```
$ convox api get /apps
[
{
"balancer": "app1-1337570912.us-east-1.elb.amazonaws.com",
"name": "app1",
"release": "",
"status": "running"
},
{
"balancer": "sinatra-1825510851.us-east-1.elb.amazonaws.com",
"name": "sinatra",
"release": "RBZJSGJVLEE",
"status": "running"
},
{
"balancer": "",
"name": "worker",
"release": "RULMHDWAIUG",
"status": "running"
}
]
```
=> add api get command

api/controllers/apps.go, api/models/app.go, api/models/process.go
This maps Racks only see apps that they created. Old apps created before this code will be seen by all Racks.
=> Apps scoped to rack

api/Dockerfile, api/cmd/build/main.go, api/controllers/builds.go, client/builds.go, client/client.go, cmd/convox/builds.go
```
$ convox build https://github.com/convox-examples/sinatra
Cloning into '/tmp/repo712923912/clone'...
Checking connectivity... done.
RUNNING: docker build -t mxgenshgwc /tmp/repo712923912/clone
Sending build context to Docker daemon 89.09 kB
Sending build context to Docker daemon
Step 0 : FROM gliderlabs/alpine:3.2
---> 5bd56d818842
...
```
=> Allow builds from repository URLs

api/dist/kernel.json, ci/dependencies-pre.sh, ci/examples/httpd/Readme.md, ci/examples/httpd/docker-compose.yml, ci/test-post.sh, ci/test-pre.sh, ci/test.sh, ci/tests/create-httpd.sh, circle.yml, cmd/convox/Makefile, cmd/convox/install.go, cmd/convox/login.go
Revive CircleCI Continuous Integration that installs convox, builds, deploys and tests and app, and uninstalls convox. Put all this behind a guard, so the ~20 minute test run only happens on demand via a CircleCI Paramaterized Build API call with the RUN_AWS variable.
=> Continuous Integration

api/cmd/build/main.go, api/controllers/builds.go, api/manifest.yml, api/manifest/manifest.go, api/manifest/manifest_test.go, api/models/build.go, client/builds.go, client/client.go, cmd/convox/builds.go, cmd/convox/deploy.go, cmd/convox/start.go
Allows use of these commands without the Docker cache
=> Add --no-cache option to build and deploy

api/models/fixtures/web_external_internal.json, api/models/fixtures/web_postgis.json, api/models/fixtures/web_postgis_internal.json, api/models/fixtures/worker.json, api/models/helpers.go
Should make CPU metric more meaningful
=> Make CPU share scale with Memory

api/controllers/api.go, api/controllers/apps.go, api/controllers/builds.go, api/controllers/controllers.go, api/controllers/environment.go, api/controllers/error.go, api/controllers/formation.go, api/controllers/processes.go, api/controllers/releases.go, api/controllers/services.go, api/controllers/switch.go, api/controllers/system.go, api/httperr/httperr.go
This wraps errors to capture proper stack traces and distinguish user and system errors.
=> Better error stack traces

api/controllers/environment.go, api/models/environment.go, client/client.go, client/environment.go, cmd/convox/env.go
also adds --promote to do this automatically
closes #47
=> give instructions for promoting a release after env update

api/controllers/processes.go, api/manifest.yml, client/processes.go, client/services.go, cmd/convox/ps.go, cmd/convox/services.go
* process api turns off stats if `?stats=false`
* add `--stats` to `convox ps`
=> add --stats to ps

api/models/service.go
=> display a url for the papertrail service

cmd/convox/builds.go, cmd/convox/deploy.go
- refactor and fix build cmd to pipe stdout but not close
- print all open ports and balancer url
=> show url(s) after deploy

api/models/formation.go, cmd/convox/scale.go
=> convox scale shows actual and desired process counts

api/Godeps/Godeps.json, api/Godeps/_workspace/src/github.com/convox/rack/test/aws_cycles.go, api/controllers/environment_test.go, api/models/environment.go, test/aws_cycles.go
=> Block environment set while creating

api/models/formation.go
I believe this fixes #123, but I didn't manage to scaffold a working test file nor did I deploy and test it manually. :-1:
=> fixes scaling of memory without count

api/workers/cluster.go
https://github.com/convox/rack/issues/65
This is a nice refactor of the mission critical cluster monitoring worker that should be save to bring into master.
There was also a plan to add additional docker checks to this system, which is laying in wait but not turned on. See the issue for more details.
=> Automatic Unhealthy Instance Termination Refactor

circle.yml
- removes "|| true" in places you need to see failures
- uses circle branch whitelisting insteaad of ENV var
to only run commits to master
=> fix circle

cmd/convox/login.go, cmd/convox/login_test.go, test/exec.go
just saying "error logging in" does not include enough info
=> show the actual login error

api/dist/kernel.json
=> Changed the line added on /etc/sysconfig/docker to append the OPTIONS on docker config instead of overwriting it

api/models/environment.go
This can be used to store things like private docker registry credentials, and an ssh private key.
/cc @csquared
=> GetRackSettings and PutRackSettings to securely get and set sensitive credentials for the rack

cmd/convox/stdcli/stdcli.go
=> downcase dir name when deriving app name from it

Dockerfile, api/controllers/ssl.go, api/models/ssl.go, client/ssl.go, cmd/convox/ssl.go
user can specify --chain for intermediate certs,
otherwise they will be auto-generated
=> handle ssl certificate chains

api/models/instances.go
=> use instance private ip for SSH

api/main.go, api/models/process.go, api/models/process_test.go, api/models/release.go, api/workers/services.go, test/aws_httpd_cycles.go
On boot and every minute after, check the latest ECS Service Events for any sign of trouble. Notify
=> Rack-wide capacity monitoring.

api/models/release.go
post cf template to s3 then use URL to avoid template size restrictions
=> release app via s3 template

api/models/cluster.go, api/models/cluster_test.go, api/workers/services.go
would rather pass back the messages than have a custom one
=> pass aws message back with some formatting

api/controllers/system.go
rename `system:update` to `rack:update` -> grid works with both names
=> call it rack:update

api/models/kernel.go
Also factor the URL out into a const.
=> Use HTTPS url for accessing kernel.json

api/dist/kernel.json, docker-compose.yml
Goes with https://github.com/convox/agent/pull/10
=> Agent 0.51

checklists/branch-release.md, checklists/master-release.md
create checklists for releases that are close to the code and executable with `checkcheckit`. it might be time for checkcheckit 2.0 :P
=> [wip] release checklist(s)

api/models/process.go
batches requests to `DescribeStacks` into groups of 10 in the `models.GetAppServices` call
=> have to batch service requests into groups of 10

api/dist/kernel.json
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment
ASG and Load Balancer depends on GatewayAttachment
=> CF dependencies

ci/release.sh, ci/track.sh, circle.yml
wrapper script that executes the command and tracks result in segment
=> CI Metrics and Auto Publish

api/manifest/manifest.go
fixes a bug in `convox start`: there's an error if you link to a container that is built instead of an image -> docker pull fails.
in this PR we don't pull and inspect built images
=> dont pull/inspect containers with no images

cmd/convox/start.go
@gmelika, this is continuation of https://github.com/convox/rack/pull/294
=> add a `--no-cache` option to `convox start`

ci/tests/create-httpd.sh, ci/tests/example-app, ci/track.sh, circle.yml
add a CI test that clones an app and runs it through more convox commands
=> moar ci tests

api/manifest/manifest.go
This is to add support for the `dockerfile` config option as described here: https://docs.docker.com/compose/compose-file/#dockerfile
=> add support for docker-compose's `dockerfile` config option

api/models/app.go
fixes #336 
@ddollar thanks for your pointers today.  Originally I merged in the environment from the manifest, but it was missing `PROCESS`, `RELEASE`, etc.  Instead, I pulled in the environment from the ECS Task Definition.  Now attached runs match detached runs match the running task itself.
Tested locally as we discussed.
I'm still new to Go -- if there are more idiomatic ways to code this I'm happy to fix it!
=> RunAttached uses environment from ECS Task Definition

api/cmd/formation/handler/kms.go, api/dist/kernel.json, ci/install.sh, cmd/convox/install.go
=> KMS Key Deletion

api/cmd/formation/handler/kms.go, api/dist/kernel.json, ci/install.sh, cmd/convox/install.go
=> Revert "KMS Key Deletion"

api/controllers/parameters.go, api/controllers/routes.go, api/manifest.yml, client/parameters.go, cmd/convox/apps.go, cmd/convox/rack.go
```
$ convox apps params -a demo
NAME                   VALUE
Cluster                convox-Cluster-1EQQWK182GWYD
Cpu                    200
Environment            https://demo-settings-4x5anpcfkhvw.s3.amazonaws.com/releases/RVYDIHTXELB/env
Key                    ...
Release                ...
Repository
Subnets                subnet-8ea696a5,subnet-95a841e3,subnet-5387870a
VPC                    vpc-08c5726c
Version                20160124182747
WebDesiredCount        1
WebMemory              256
WebPort443Balancer     443
WebPort443Certificate
WebPort443Host         8142
WebPort443Secure       No
WebPort80Balancer      80
WebPort80Certificate
WebPort80Host          13413
WebPort80Secure        No
​
$ convox apps params set Foo=bar -a demo
Updating parameters... ERROR: ValidationError: …
```
=> add advanced params get/set

api/cmd/formation/handler/kms.go, api/dist/kernel.json, ci/install.sh, cmd/convox/install.go
revert the revert. See:
https://github.com/convox/rack/issues/279
https://github.com/convox/rack/pull/337
https://github.com/convox/rack/pull/342
=> KMS Deletion

api/cmd/monitor/main.go, api/controllers/formation.go, api/controllers/routes.go, api/controllers/system.go, api/dist/kernel.json, api/manifest.yml, api/models/formation.go, api/models/system.go, api/workers/autoscale.go, client/system.go, docker-compose.yml
=> autoscale rack count

Dockerfile
=> vendor compiled cfssl binary

api/controllers/processes.go, api/models/app.go, client/processes.go, cmd/convox/exec.go, cmd/convox/run.go
fixes strange wrapping issues with run and exec
=> fix width/height issues with run and exec

cmd/convox/builds.go
=> incremental build fallback

api/controllers/builds.go, api/controllers/routes.go, api/models/build.go, api/models/manifest.go, api/models/release.go, client/builds.go, cmd/convox/builds.go
Copy a build to another app
```
$ cd httpd
$ convox builds
ID           STATUS    RELEASE      STARTED       ELAPSED  DESC
BMGFRJDDMOZ  complete  RIEDZQOAQMA  3 hours ago   18s          
BSXRDHUHLJY  complete  RPSROUYPGTI  23 hours ago  19s          
BUTXPMTFNLN  complete  RDAMDSUDGXK  23 hours ago  19s          
BWBEYNTYLSP  complete  RSSCMPCETRY  2 days ago    53s          
BTTLXDFRUAA  complete  RYHJIDMCERF  2 days ago    6s           
...
$ convox builds copy BMGFRJDDMOZ httpd-new --app httpd
Copying build... OK
To deploy this copy run `convox releases promote REXLWCBECZG --app httpd-new`
$ convox builds --app httpd-new
ID           STATUS    RELEASE      STARTED         ELAPSED  DESC                     
BFCEHIGBKQV  complete  REXLWCBECZG  37 seconds ago  1s       Copy of httpd …
```
=> Build Copy

api/models/index.go, cmd/convox/builds.go
=> add max concurrency to index operations

api/controllers/builds.go, api/helpers/helpers.go, api/httperr/httperr.go, api/models/build.go
* standardize build events into `build-success` and `build-error`
* track elapsed time of successful builds
=> standardize build events

api/manifest/manifest.go
I think? Took approach from `generateId` in model helpers. Seems like it would exist as a top-level helper but don't know goland approach for this sort of thing.
=> prefix the tag for builds

cmd/convox/builds.go, cmd/convox/deploy.go
=> enable --incremental with deploy

client/client.go
=> Proxy websocket connections over HTTPS_PROXY if it is set

api/controllers/services.go
=> bugfix in service stack name validation

cmd/convox/install.go, cmd/convox/install_test.go
=> validate stack name against ecr regex

client/client.go
=> handle proxy without auth

api/controllers/formation.go, api/controllers/formation_test.go, api/models/app.go, api/models/formation.go, api/models/process.go, api/provider/test.go, test/aws_cycles.go
=> bugfix: no count form input was turning into a scale 0 update

api/dist/kernel.json
Quickfix from testing https://github.com/convox/rack/pull/408
=> -e flag is incorrectly causing a rollback on every update

client/client.go
=> more websocket proxy fixes

cmd/convox/scale.go
=> tighten up scale validate and usage

api/cmd/build/main.go, api/controllers/builds.go, api/manifest.yml, api/models/build.go, client/builds.go, cmd/convox/builds.go, cmd/convox/builds_test.go, cmd/convox/deploy.go
=> Build API takes commit-ish and description

api/manifest/manifest.go
=> Bail out on invalid link names

api/manifest.yml, api/provider/aws/system.go, api/structs/system.go, client/system.go, cmd/convox/rack.go
=> include region in system API and display

api/manifest/manifest.go
runs remove as detached docker exec
=> fix file sync removal problem

api/models/app.go, api/models/service.go, api/provider/aws/aws.go, cmd/convox/install.go, cmd/convox/install_test.go
=> fixes #397. single regex to validate rack, app and service name

cmd/convox/login.go
=> default login host

api/controllers/racks.go, api/controllers/routes.go, client/client.go, client/racks.go, cmd/convox/racks.go, docker-compose.yml
=> implement a racks command for listing racks

api/models/app.go, api/models/ssl.go, cmd/convox/ps.go
Taking over for 
* https://github.com/convox/rack/pull/446 Try to cleanup S3 buckets on app deletion
* https://github.com/convox/rack/pull/469 Let CF implement SSL updates
* https://github.com/convox/rack/pull/479 Fix ps CPU output
cc @anthonyrisinger and @mwarkentin
=> Bugfixes in app cleanup, ps stats and SSL update

README.md
A couple of very minor punctuation edits on README.md. Excellent new README, btw.
=> punctuation

api/models/service-papertrail.go
=> papertrail service needs CAPABILITY_IAM

api/cmd/build2/main.go, api/manifest/manifest.go
a brutally simple exponential backoff algorithm for retrying pushes and pulls
=> retry push and pull

api/dist/kernel.json
- https://github.com/convox/rack/pull/502 disable automatic updates of kernel* packages
- https://github.com/convox/rack/pull/497 Suspend scheduled actions during rack updates
=> Convox Update Enhancements

api/dist/kernel.json
I want to release this with https://github.com/convox/rack/pull/509
=> amzn-ami-2015.09.g-amazon-ecs-optimized

api/dist/kernel.json
This reverts commit d8db8c91f852633684b8dbbd6dbcb4f0a83540e7.
=> Revert "amzn-ami-2016.03.a-amazon-ecs-optimized"

api/cmd/formation/handler/ecr.go, api/cmd/formation/handler/ecs.go, api/cmd/formation/handler/kms.go
=> Fix more Custom Resource updaters

api/controllers/builds.go, api/manifest.yml, api/manifest/manifest.go
=> Build enhancements

api/manifest/manifest.go, api/manifest/manifest_test.go, cmd/convox/start.go, examples/compose/docker-compose.yml
also displays a warning if the app dir is mounted as a volume
=> default sync to true in convox start

cmd/convox/builds.go
=> Restore formatting on build messages

README.md
https://aws.amazon.com/about-aws/whats-new/2016/03/amazon-ec2-container-registry-available-in-eu-ireland/
[ci skip]
=> readme: ECR is now available in eu-west-1

api/models/manifest.go
=> remove hard-coded label prefix

api/manifest/manifest.go, api/models/fixtures/environment_map.json, api/models/fixtures/environment_map.yml, api/models/manifest.go, api/models/manifest_test.go, api/models/release.go
- Handle environment section in map format #578 
- fix check for proxy locally #583
- Sub underscores for hyphens #582
=> Release 20160426

api/manifest/manifest.go, cmd/convox/helpers.go, cmd/convox/install.go, cmd/convox/login.go, cmd/convox/start.go, cmd/convox/stdcli/stdcli.go
=> Quality of Service Measurements

cmd/convox/install.go, cmd/convox/start.go
=> namespace cli events

cmd/convox/install.go
=> prompt for email earlier in install

api/models/environment.go, cmd/convox/run.go
Combines:
#630 To validate the process ID
#627 Not getting the env settings if app status is creating.
=> Release 20160513

api/manifest/manifest.go
=> disable bidirectional sync from deleting host-side files

cmd/convox/uninstall.go
=> fix position for uninstall credential file arg

.travis.yml, api/manifest/manifest.go, cmd/convox/start.go
=> Handle docker tag -f deprecation

api/models/release.go
=> VPCCIDR fix for promoting an app

api/manifest/manifest.go
=> handle non-root build contexts and relative destination dirs in copy

api/models/formation.go
=> Formation shouldnt error on stacks without Cpu parameter

cmd/convox/install.go, cmd/convox/install_test.go
=> remove user policy validation until it can be corrected

cmd/convox/start.go, cmd/convox/stdcli/stdcli.go
=> better monitoring of convox start

api/dist/kernel.json
With https://github.com/convox/rack/pull/860
=> agent 0.70 to address convox/agent panic and log forwarding failure

cmd/convox/install.go, cmd/convox/uninstall.go
if the aws cli is installed and configured this will now try to read the credentials from your current profile if you haven't specified any as flags
=> use aws cli to generate credentials if available

api/controllers/instances.go, test/aws_cycles.go
=> Convox kill terminate asg

api/models/release.go, ci/cleanup.sh, ci/dependencies-pre.sh, ci/install.sh, ci/tests/example-app, ci/tests/example-apps, circle.yml, cmd/convox/apps.go, cmd/convox/install.go, cmd/convox/releases.go, cmd/convox/scale.go
- Tests rails and django examples in parallel
=> CI stability and coverage

api/controllers/apps.go, api/controllers/apps_test.go, api/controllers/builds.go, api/controllers/builds_test.go, api/controllers/releases.go, api/controllers/system.go, api/models/app.go, api/models/release.go, api/provider/aws/apps.go, api/provider/aws/aws.go, api/provider/aws/builds.go, api/provider/aws/builds_test.go, api/provider/aws/releases.go, api/provider/aws/releases_test.go, api/provider/provider.go, api/provider/test.go, api/structs/app.go, manifest/build.go, manifest/build_test.go, manifest/process.go
- closes #978 Cleanup after app deletion [@MiguelMoll]
- closes #991 use go-homedir for cross-compilability [@ddollar]
- closes #1002 dont push 5 times [@awsmsrc]
- closes #1004 dont require a label set to tcp [@ddollar]
=> [RELEASE] 20160808

api/cmd/formation/handler/ecs.go
need to replace services if their roles change
=> replace a service during a role change

Dockerfile, changes/changes.go, ci/region.sh, cmd/convox/stdcli/table.go, manifest/run.go, provider/aws/dist/rack.json, provider/aws/system.go, provider/aws/system_test.go
- closes #1040 Validate ec2 instance type when scaling [@MiguelMoll]
- closes #1043 Make stopping of local containers more graceful [@bladealslayer]
- closes #1062 fix pct-based output regression [@ddollar]
- closes #1064 Explicit build call for `monitor` added [@MiguelMoll]
- closes #1065 prevent panics on dockerignore recursion [@ddollar]
- closes #1067 reorder regions for ci [@ddollar]
- closes #1068 Lambda dep tweak [@MiguelMoll]
- closes #1069 fix reverted ecs amis [@ddollar]
=> [RELEASE] 20160815

api/models/release.go, provider/aws/dist/rack.json
- closes #1104 only randomize the instance ports for old apps [@ddollar]
- closes #1105 Tweak deployment settings for monitor [@ddollar]
=> [RELEASE] 20160819-2

api/structs/service.go, provider/aws/service.go
- closes #1108 Fix services info, url, and delete [@ddollar]
=> [RELEASE] 20160819-3

Godeps/Godeps.json, api/models/docker.go, api/models/instances.go, api/models/process.go, api/workers/cluster.go, cmd/convox/stdcli/stdcli.go, provider/aws/aws.go, provider/aws/builds.go, provider/aws/capacity.go, provider/aws/instances.go, provider/aws/instances_test.go, provider/aws/releases.go, provider/aws/service.go, provider/aws/system.go, test/aws_cycles.go, vendor/github.com/convox/version/version.go
- closes #1109 Fix List container instances everywhere [@nzoschke]
- closes #1114 Exit 1 when command not found [@awsmsrc]
- closes #1116 version package bump [@nzoschke]
- closes #1125 Add missing parameters for webhook service [@MiguelMoll]
- closes #1132 Validate parameter is not an empty string for S3 and SNS [@MiguelMoll]
=> [RELEASE] 20160824

api/models/app.go, api/models/app_test.go, api/models/cronjob.go, api/models/process.go, ci/install.sh, ci/report.sh, manifest/process.go, manifest/process_test.go, provider/aws/instances.go, provider/aws/instances_test.go, provider/aws/lambda/fluentd/main.go, provider/aws/lambda/fluentd/main_test.go, provider/aws/templates/service/postgres.tmpl, test/aws_cycles.go
- closes #1112 Updating FluentD service w/ fixes [@adamenger]
- closes #1124 Update postgres version to latest 9.5.2 [@lisajluo]
- closes #1131 fix range references in cronjobs function [@awsmsrc]
- closes #1137 Normalize DescribeInstances calls [@nzoschke]
- closes #1139 wrap string commands in sh -c [@ddollar]
=> [RELEASE] 20160825

api/controllers/builds.go, api/models/cronjob.go, api/models/fixtures/Makefile, api/models/fixtures/cron_labels.json, api/models/fixtures/cron_labels.yml, bin/ci-cleanup, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/templates/service/fluentd.tmpl, provider/provider.go, provider/test.go
- closes #1142 Cron Job Rule name validation fix [@nzoschke]
- closes #1144 point to correct fluentd lambda code [@ddollar]
- closes #1147 Lessen chance of throttling during builds [@nzoschke]
- closes #1148 clean up iam roles in ci-cleanup [@ddollar]
=> [RELEASE] 20160826

api/controllers/apps.go, api/controllers/system.go, api/structs/options.go, provider/aws/capacity.go, provider/aws/capacity_test.go, provider/aws/formation_test.go, provider/aws/logs.go, provider/aws/logs_test.go
- closes #1187 take all deployments into account for capacity width [@ddollar]
- closes #1188 fetch logs in chunks and sort [@ddollar]
=> [RELEASE] 20160904

api/cmd/build/Dockerfile, api/cmd/build/main.go, api/cmd/build/source/git.go, bin/ci-cleanup, cmd/convox/builds.go, provider/aws/builds.go, provider/aws/builds_test.go
- closes #1259 ci cleanup script [@ddollar]
- closes #1263 Properly support ecr repos for build auth [@ddollar]
- closes #1264 Handle SSH builds using SSH keys [@ddollar]
=> [RELEASE] 20160927

.travis.yml, api/cmd/build/source/git.go, api/controllers/builds.go, client/builds.go, cmd/convox/install.go, cmd/convox/rack.go, cmd/convox/rack_test.go, manifest/manifest.go, manifest/manifest_test.go, provider/aws/builds.go, provider/aws/builds_test.go
- closes #1260 fix dockerfile in v1 docker-compose [@ddollar]
- closes #1270 Accept AWS_DEFAULT_REGION as well as AWS_REGION when running `convox install` [@soulshake]
- closes #1273 stop at required updates [@ddollar]
- closes #1274 Fixes for build API regressions [@ddollar]
- closes #1275 ECR login improvements [@mattmanning]
=> [RELEASE] 20160929

client/builds.go, client/client.go, client/client_test.go, provider/aws/capacity.go, provider/aws/capacity_test.go, provider/aws/dist/rack.json, provider/aws/system.go
- closes #1325 Client improvements for export and import [@MiguelMoll]
- closes #1343 paginate services [@ddollar]
- closes #1351 update ecs amis [@ddollar]
- closes #1352 small typo fix [@MiguelMoll]
=> [RELEASE] 20161026

provider/aws/dist/rack.json, provider/aws/system.go
- closes #1357 Fix rack status precedence [@MiguelMoll]
- closes #1360 flesh out us-east-2 mappings [@ddollar]
=> [RELEASE] 20161031

Development.md, api/controllers/system.go, api/controllers/system_test.go, api/models/fixtures/web_redis.json, api/models/fixtures/web_redis.yml, api/models/release.go, client/client.go, cmd/convox/install.go, manifest/service.go, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/dist/rack.json
- closes #1370 Use `LINK_PORT` variable if it's set [@mwarkentin]
- closes #1394 Clean up old builds [@MiguelMoll]
- closes #1395 Rack instance count must be >= 3 [@MiguelMoll]
- closes #1397 Add last line to docker error [@MiguelMoll]
- closes #1402 Reuse certs [@nzoschke]
=> [RELEASE] 20161116

api/models/helpers.go, cmd/convox/start.go, provider/aws/dist/rack.json
- closes #1422 Stop start hiding errors [@awsmsrc]
- closes #1423 update_rollback_failed -> error [@awsmsrc]
- closes #1426 Update AMIs. [@soulshake]
=> [RELEASE] 20161130

cmd/convox/install.go, cmd/convox/install_test.go, docker-compose.yml, provider/aws/dist/rack.json, provider/aws/lambda/lifecycle/main.go, provider/aws/system.go, provider/aws/system_test.go
- closes #1433 fix output var formatting for env [@ddollar]
- closes #1435 Return stdcli.Error(err) instead of stdcli.QOSEventSend(...). [@soulshake]
- closes #1436 Minsize count [@MiguelMoll]
- closes #1440 New stack outputs [@MiguelMoll]
=> [RELEASE] 20161205

ci/region.sh, cmd/convox/install.go, cmd/convox/stdcli/stdcli.go, manifest/build.go, manifest/build_test.go, provider/aws/dist/rack.json
- closes #1447 Conditions added to the gateway stack outputs [@MiguelMoll]
- closes #1448 windows support [@ddollar]
=> [RELEASE] 20161208

cmd/convox/start.go, manifest/run.go, sync/sync.go
- closes #1472 Bypass temp dir for incoming files [@MiguelMoll]
- closes #1473 Stop local containers on convox start error [@MiguelMoll]
=> [RELEASE] 20161214

cmd/convox/install.go
The parameter was not being properly set, so the resulting stack was not being created correctly.
=> Set CF InternetGateway parameter based on CLI input

api/workers/autoscale.go, cmd/convox/exec.go, cmd/convox/start.go, manifest/exec.go, manifest/labels.go, manifest/run.go
- closes #1482 --no-build flag for convox start [@MiguelMoll]
- closes #1483 make start scanner buffer 10mb [@ddollar]
- closes #1484 fix extraneous error on convox exec [@ddollar]
- closes #1486 Return if no change in system count [@MiguelMoll]
- closes #1490 edit labels in place and shift all labels with ports [@ddollar]
=> [RELEASE] 20161219

manifest/process.go
NFTS -> container is not working. Use normal docker volume.
=> Disable OS File Sharing on Windows

cmd/convox/apps_test.go, cmd/convox/ssl.go, cmd/convox/stdcli/stdcli.go, manifest/fixtures/dir-name-with-dots/foo.bar/Dockerfile, manifest/fixtures/dir-name-with-dots/foo.bar/docker-compose.yml, provider/aws/processes.go, sync/sync.go
- closes #1459 App name with dots [@soulshake]
- closes #1489 [WIP] Prevent file sync from locking up when syncing large amount of files [@MiguelMoll]
- closes #1499 Fix host path for one-off volumes [@mattmanning]
- closes #1500 update ssl update help [@ddollar]
=> [RELEASE] 20161222

test/server.go
actual, expected --> expected, actual
=> Flip stubbed request body assertion arguments

client/processes.go, cmd/convox/apps.go, cmd/convox/deploy.go, cmd/convox/rack.go, cmd/convox/releases.go, cmd/convox/scale.go, cmd/convox/ssl.go, provider/aws/service.go, provider/aws/service_test.go, sync/sync.go
- closes #1517 make sure we process changes as they come [@ddollar]
- closes #1522 Reinstate `ssl update` `--rack` and `--app` flags [@pmcnr-hx]
- closes #1527 Add CONVOX_WAIT envvar CLI option [@soulshake]
- closes #1531 prevent `convox exec` and friends from hanging on error [@ddollar]
- closes #1532 stop handling old-style services [@ddollar]
=> [RELEASE] 20170109

cmd/convox/install.go, provider/aws/dist/rack.json
- closes #1063 Create KernelUser's managed policy [@MiguelMoll]
=> [RELEASE] 20170112

provider/aws/dist/rack.json
Also added IAM perms in a separate policy as kernel user was getting too big and hitting size limits.
=> Add more permissions for a private Rack

circle.yml
Update CircleCI timeouts for regions that take a while to install
=> CircleCI timeout

ci/install.sh, cmd/convox/install.go, provider/aws/dist/rack.json, provider/aws/processes.go, provider/aws/registries.go, provider/aws/registries_test.go
- closes #1548 Paginate task listings [@ddollar]
- closes #1604 Validate required `registries add` args [@ianmalott]
- closes #1615 New strategy for Rack service replacement [@ddollar]
- closes #1616 readonly ecr permissions [@MiguelMoll]
- closes #1621 option to disable autoscale during install [@MiguelMoll]
=> [RELEASE] 20170125-2

cmd/convox/env.go
=> Add --wait when promoting and env update

api/cmd/build/main.go, api/controllers/apps_test.go, api/controllers/builds.go, client/client.go, cmd/convox/api_test.go, cmd/convox/deploy.go, cmd/convox/deploy_test.go, cmd/convox/doctor.go, cmd/convox/install.go, cmd/convox/install_test.go, cmd/convox/login.go, cmd/convox/main.go, cmd/convox/services.go, cmd/convox/start.go, cmd/convox/stdcli/stdcli.go, cmd/convox/uninstall.go, manifest/build.go, manifest/build_test.go, manifest/exec.go, manifest/push.go, manifest/run.go, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/event.go, provider/aws/resource.go, test/http.go, test/server.go
- closes #1684 Recover --rack from os.Args if urfave/cli has dropped it [@soulshake]
- closes #1910 Check docker-compose exists and validate file before deploy [@MiguelMoll]
- closes #1914 Build Environment Limit Fix [@mattmanning]
- closes #1915 Fix errant capitalization and trailing periods in usage strings and error messages [@soulshake]
- closes #1916 only log the command to run [@MiguelMoll]
- closes #1917 build events includes id, timestamp and from [@nzoschke]
- closes #1918 Export client.Request and add TestApiGetRequest [@soulshake]
=> [RELEASE] 20170210

cmd/convox/appinit/simpleapp.go
=> remove debug log

docker-compose.yml, provider/aws/dist/rack.json, provider/aws/formation.go, provider/aws/formation_test.go, provider/aws/system.go, provider/aws/system_test.go
- closes #2037 add cf notifcation env var to the monitor [@MiguelMoll]
=> [RELEASE] 20170309

Development.md, api/models/environment.go, api/models/environment_test.go, bin/current-ecs-amis, cmd/convox/install.go, cmd/convox/main.go, cmd/convox/releases_test.go, cmd/convox/scale.go, cmd/convox/scale_test.go, cmd/convox/stdcli/stdcli.go, cmd/convox/stdcli/stdcli_test.go, provider/aws/dist/rack.json
- closes #1930 Add CF Resource metadata [@ianmalott]
- closes #2039 'convox scale' should not exit silently if app not found [@soulshake]
- closes #2040 Document build image in Development.md [@soulshake]
- closes #2048 Respect --app flag regardless of position [@soulshake]
- closes #2049 Return error if CONVOX_DEBUG, CONVOX_WAIT or RACK_PRIVATE aren't set to valid boolean values [@soulshake]
- closes #2055 Env set enhancement [@SonOfBytes @MiguelMoll]
- closes #2057 Ami updates [@MiguelMoll]
- closes #2058 allow an http proxy to be specified [@ddollar]
=> [RELEASE] 20170315

cmd/convox/apps.go
Removing app deletion prompt to keep compatibility with existing scripts.
N/A
Verify app deleting works as expected.
=> remove app deletion prompt to keep compatibility with existing scripts

api/models/environment.go, api/models/environment_test.go, cmd/convox/rack.go
- closes #2131 fix rack info [@ddollar]
- closes #2132 remove restrictions from env parser [@ddollar]
=> [RELEASE] 20170405

api/models/release.go, provider/aws/builds_test.go, provider/aws/dist/rack.json, provider/aws/formation_test.go, provider/aws/processes_test.go, provider/aws/releases.go, provider/aws/releases_test.go
- closes #2097 remove env vars from dynamo for new releases, only use encrypted s3 [@MiguelMoll]
- closes #2140 agent 0.71 [@nzoschke]
=> [RELEASE] 20170407

provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/dist/rack.json, provider/aws/docker.go, provider/aws/lambda/cfevents/main.go, provider/aws/lambda/ecsevents/main.go
- closes #2076 More HTTP Proxy [@mattmanning]
- closes #2143 use novalue instead of false because so asg doesn't freak out [@ddollar]
- closes #2144 avoid DescribeStacks call during event logging [@ddollar]
- closes #2147 BuildRelease sets last release decrypted env in new release [@nzoschke]
=> [RELEASE] 20170412

provider/aws/formation_test.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/aws/system_test.go, vendor/github.com/kballard/go-shellquote/LICENSE, vendor/github.com/kballard/go-shellquote/README, vendor/github.com/kballard/go-shellquote/doc.go, vendor/github.com/kballard/go-shellquote/quote.go, vendor/github.com/kballard/go-shellquote/unquote.go
- closes #2152 fix DescribeInstances throttling [@ddollar]
=> [RELEASE] 20170414

api/workers/events.go
- closes #2161 Verify service name is from an app or rack [@MiguelMoll]
=> [RELEASE] 20170420

api/cmd/build/main.go, provider/aws/dist/rack.json
This is PR is currently stacked on top of https://github.com/convox/rack/pull/2150. Once that PR is merged this can be rebased for easier diff viewing.
This enhances the aforementioned Secure Environment feature by making the same strategy available at build time.
The `secure-environment` binary available [here](https://github.com/convox/secure-environment) can be used inside the Dockerfile to fetch and decrypt the environment file stored on S3.
To support `secure-environment` functionality, a few Docker ARGs must be enumerated. These are:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_REGION`
- `SECURE_ENVIRONMENT_KEY`
- `SECURE_ENVIRONMENT_URL`
See the Dockerfile at  [https://github.com/convox-examples/secure-env-example](https://github.com/convox-examples/secure-env-example) …
=> Secure build

api/cmd/build/source/git.go, provider/aws/dist/rack.json
- closes #2167 Update Submodules when building from git [@mattmanning]
- closes #2170 limit account events to specified resources [@MiguelMoll]
=> [RELEASE] 20170426

api/models/environment.go, api/models/environment_test.go
- closes #2173 remove single quotes from env vars [@MiguelMoll]
=> [RELEASE] 20170427

manifest/process.go, provider/aws/dist/rack.json
- closes #2175 support privileged in convox start [@ddollar]
- closes #2176 add param to disable agent [@ddollar]
=> [RELEASE] 20170501

Godeps/Godeps.json, manifest/build_test.go, manifest/fixtures/specific-service.yml, manifest/manifest.go, vendor/github.com/twmb/algoimpl/LICENSE, vendor/github.com/twmb/algoimpl/go/graph/functions.go, vendor/github.com/twmb/algoimpl/go/graph/graph.go, vendor/github.com/twmb/algoimpl/go/graph/graph_heap.go, vendor/github.com/twmb/algoimpl/go/graph/lite/litegraph.go, vendor/github.com/twmb/algoimpl/go/graph/search.go, vendor/github.com/twmb/algoimpl/go/graph/todo.md
Build a directed acyclical graph of links and do a topological sort on it to determine process run order for `convox start`.
=> Determine process run order via topological sort

Godeps/Godeps.json, manifest/build_test.go, manifest/fixtures/specific-service.yml, manifest/manifest.go, vendor/github.com/twmb/algoimpl/LICENSE, vendor/github.com/twmb/algoimpl/go/graph/functions.go, vendor/github.com/twmb/algoimpl/go/graph/graph.go, vendor/github.com/twmb/algoimpl/go/graph/graph_heap.go, vendor/github.com/twmb/algoimpl/go/graph/lite/litegraph.go, vendor/github.com/twmb/algoimpl/go/graph/search.go, vendor/github.com/twmb/algoimpl/go/graph/todo.md
- closes #2182 Determine process run order via topological sort [@mattmanning]
=> [RELEASE] 20170502

manifest/manifest.go
- closes #2187 only start a service and its dependencies when specified to convox start [@mattmanning]
=> [RELEASE] 20170508

client/processes.go
=> Close stream to prevent cli from hanging

api/controllers/builds.go, dist/haproxy.cfg, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/dist/rack.json
- closes #2217 Reliable build export [@MiguelMoll]
- closes #2219 ami updates [@MiguelMoll]
=> [RELEASE] 20170607

api/controllers/builds.go, api/controllers/builds_test.go, provider/aws/dist/rack.json
- closes #2217 Reliable build export [@MiguelMoll] via #2220
- closes #2221 do not delete build of active release [@MiguelMoll]
- closes #2224 Revert AMI images [@MiguelMoll]
=> [RELEASE] 20170613

provider/aws/builds.go, provider/aws/dist/rack.json, provider/aws/processes.go, provider/aws/processes_test.go
- closes #2226 Apply TaskRole to run TaskDefinition [@mattmanning]
- closes #2227 iterate over all imported tags [@MiguelMoll]
- closes #2228 ami updates [@MiguelMoll]
=> [RELEASE] 20170619

.travis.yml, manifest/fixtures/interpolate-env-var.yml, manifest/interpolate.go, manifest/manifest_test.go, provider/aws/dist/rack.json
- closes #2230 take brackets into account for variable expansion [@MiguelMoll]
- closes #2231 Add ec2:DescribeNetworkInterfaces IAM permission [@mattmanning]
- closes #2235 ami updates [@MiguelMoll]
=> [RELEASE] 20170622

cmd/convox/certs.go, provider/aws/dist/rack.json, provider/aws/resource.go
- closes #2239 don't generate random password if one has been provided [@mattmanning]
- closes #2242 `certs generate` should take minimum 1 argument, not exactly 1 [@mattmanning]
- closes #2243 ami updates [@MiguelMoll]
=> [RELEASE] 20170629

api/cmd/build/clean.go, api/crypt/crypt.go, api/models/docker.go, api/models/release.go, api/workers/cluster.go, cmd/convox/appinit/ruby.go, cmd/convox/appinit/simpleapp.go, cmd/convox/doctor.go, cmd/convox/install.go, cmd/convox/login.go, cmd/convox/start.go, provider/aws/lambda/fluentd/main.go, provider/aws/lambda/formation/handler/ecs.go, provider/aws/processes.go, sync/sync.go
- closes #2247 Fix Swallowed Errors [@alrs]
=> [RELEASE] 20170712

manifest/balancer.go, manifest/manifest.go
- closes #2262 Make health check interval settable in via docker-compose label [@mattmanning]
=> [RELEASE] 20170724

api/cmd/monitor/main.go, api/workers/spotreplace.go, provider/aws/dist/rack.json, provider/aws/instances.go, provider/aws/instances_test.go
- closes #2265 Spot Instances [@mattmanning]
=> [RELEASE] 20170802

api/workers/spotreplace.go, manifest/fixtures/v2-0.yml, manifest/fixtures/v2-1.yml, manifest/fixtures/v2-2.yml, manifest/manifest.go, manifest/manifest_test.go, provider/aws/dist/rack.json
- closes #2271 Add rack instance security group param [@william-richard]
- closes #2275 Don't count DRAINING instances in total [@mattmanning]
- closes #2276 Support a minor version number for v2 Docker Compose config files [@jamesottaway]
=> [RELEASE] 20170814

provider/aws/dist/rack.json
- closes #2280 Use convox agent 0.73 [@mattmanning]
=> [RELEASE] 20170818

api/workers/spotreplace.go, docker-compose.yml, provider/aws/dist/rack.json
- closes #2283 parameterize API desired count [@nzoschke]
- closes #2286 set ECS instance attributes on build, primary and spot instances [@nzoschke]
- closes #2287 tighten up spot replacement algorithm [@ddollar]
=> [RELEASE] 20170912

provider/aws/dist/rack.json
=> amzn-ami-2017.03.f-amazon-ecs-optimized ami ids

provider/aws/dist/rack.json
- closes #2295 Turn on EFS in ap-southeast-2 [@mattmanning]
=> [RELEASE] 20170925

REGIONS, cmd/convox/services.go, provider/aws/dist/rack.json, provider/aws/templates/resource/postgres.tmpl
- closes #2298 add another rds permission [@nzoschke]
- closes #2299 add ca-central-1 [@nzoschke]
- closes #2300 Add backup retention period for postgres RDS services. [@nzoschke]
=> [RELEASE] 20170928

bin/current-ecs-amis, provider/aws/dist/rack.json, provider/aws/processes.go, provider/aws/processes_test.go
- closes #2310 Add support for secure environment in oneoff tasks [@bladealslayer]
- closes #2314 updated ecs amis [@ddollar]
=> [RELEASE] 20171016

provider/aws/dist/rack.json, provider/aws/templates/resource/postgres.tmpl
- closes #2317 attach and detach role policies [@ddollar]
- closes #2319 Update DatabaseSnapshotIdentifier paramater Postgres template [@denmat]
=> [RELEASE] 20171020

Dockerfile, api/models/docker.go, api/models/release.go, cmd/convox/apps.go, cmd/convox/apps_test.go, provider/aws/apps.go, provider/aws/formation/rack.json
- closes #2344 upgrade docker version to support multistage builds [@ddollar]
- closes #2345 update subnet parameters on release promotion [@ddollar]
=> [RELEASE] 20171115

.dockerignore, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/template.go
- closes #2350 support multiple domains for gen2 services [@ddollar]
- closes #2352 not all accounts have 2 azs in us-west-1 [@ddollar]
=> [RELEASE] 20171116

api/models/environment.go, cmd/convox/builds.go
- closes #2354 Add short name `-d` for `--description` flag [@jmcvetta]
- closes #2355 fix environment file for gen1 [@ddollar]
=> [RELEASE] 20171120

api/models/environment.go, provider/aws/releases.go
- closes #2357 per-release env should be public for gen1 [@ddollar]
=> [RELEASE] 20171121

provider/aws/formation/rack.json, provider/aws/processes.go
- closes #2366 switch load balancer ports when switching to private api [@ddollar]
- closes #2368 load env from existing service for oneoff processes [@ddollar]
=> [RELEASE] 20171128

api/models/app.go, manifest/service.go, provider/aws/aws.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/releases.go, provider/aws/template.go
- closes #2369 Generation 2 Links and Internal Services [@ddollar]
=> [RELEASE] 20171129

provider/aws/formation/rack.json, provider/aws/releases.go, provider/aws/service.go
- closes #2386 Update ECS AMIs and tweak EBS encryption to handle ECS AMI volume layout [@ddollar]
- closes #2390 maintain certificate between releases [@ddollar]
=> [RELEASE] 20171205

manifest/manifest.go, manifest/service.go, provider/aws/formation/app.json.tmpl, provider/aws/resource.go, provider/aws/template.go
- closes #2392 gen2 agent support [@ddollar]
- closes #2393 Use correct parameters for syslog when unlinking [@ddollar]
=> [RELEASE] 2017120502

cmd/convox/install.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/instances.go
- closes #2395 updated ssh package needs key check [@ddollar]
- closes #2396 support internal dns at .convox [@ddollar]
=> [RELEASE] 20171206

cmd/convox/builds.go, cmd/convox/install.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2400 fix build delete help [@ddollar]
- closes #2404 Revert .convox DNS until we have a solution to VPC conflicts [@ddollar]
=> [RELEASE] 20171208

provider/aws/apps.go, provider/aws/environment.go, provider/aws/formation/g1/app.json.tmpl, provider/aws/releases.go
- closes #2407 Fix for new environment variables set before new build. [@radekl]
- closes #2408 use exports to reduce parameter count [@ddollar]
=> [RELEASE] 20171211

.travis.yml, cmd/build/main.go, provider/aws/processes.go, provider/aws/processes_test.go, structs/process.go
- closes #2412 Read secure env key from rack output [@ddollar]
=> [RELEASE] 20171212

manifest/build.go, manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go
You can now specify a custom Dockerfile like this:
```
service:
web:
build:
path: .
manifest: Dockerfile.other
```
=> custom dockerfile name

docker-compose.yml, provider/aws/formation/rack.json, provider/aws/releases.go, provider/aws/workers_autoscale.go
- closes #2417 add AutoscaleExtra parameter to configure breathing room [@ddollar]
- closes #2418 attempt to set old app params to allow rollback to old releases [@ddollar]
=> [RELEASE] 20171214

REGIONS, manifest1/run.go, provider/aws/formation/rack.json
- closes #2420 handle directory syncs with slashes [@ddollar]
- closes #2421 Add `BuildAutoscalingGroup` output [@mwarkentin]
- closes #2424 eu-west-3 support [@ddollar]
=> [RELEASE] 20171221

provider/aws/formation/g1/app.json.tmpl, provider/aws/releases.go
- closes #2427 remove environment parameter [@ddollar]
=> [RELEASE] 20171227

cmd/convox/install.go, manifest/service.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2435 use internal dns with rack name [@ddollar]
- closes #2436 Add Build.Manifest to BuildHash [@idris]
=> [RELEASE] 20180106

manifest1/run.go, provider/aws/releases.go, provider/aws/resource.go
- closes #2445 dont prepend context if the combination doesnt exist [@ddollar]
- closes #2447 handle old services [@ddollar]
=> [RELEASE] 20180112

bin/ci-cleanup, manifest/service.go, manifest/yaml.go, manifest1/service.go, provider/aws/formation/app.json.tmpl
- closes #2429 support ecs health check grace period [@ddollar]
- closes #2452 add IamPolicy app parameter for custom iam policy on service role [@ddollar]
- closes #2459 skip --options to add/copy for sync [@ddollar]
- closes #2461 update ci cleanup script [@ddollar]
=> [RELEASE] 20180124

provider/aws/apps_test.go, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/formation_test.go, provider/aws/helpers.go, provider/aws/object_test.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/aws/releases_test.go, provider/aws/system.go, provider/aws/system_test.go
- closes #2463 use ListStackResources instead of DescribeStackResources to overcome api limits [@ddollar]
=> [RELEASE] 20180125

cmd/convox-env/main.go, manifest1/run.go
- closes #2466 correct sync prefix when using context [@ddollar]
- closes #2467 dont interfere with usage of service policy [@ddollar]
=> [RELEASE] 2017012502

cmd/convox-env/exec_default.go, cmd/convox-env/exec_unix.go, cmd/convox-env/main.go, cmd/region-config/main.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2465 allow convox-env to pass through signals [@robinjoseph08]
- closes #2469 expose RELEASE as a task environment variable [@robinjoseph08]
- closes #2471 update ecs amis [@ddollar]
=> [RELEASE] 20180126

cmd/convox/main.go, cmd/convox/rack.go, cmd/convox/racks.go, cmd/convox/start.go, cmd/convox/switch.go, provider/aws/formation/app.json.tmpl, provider/aws/template.go
- closes #2505 allow switch to local [@ddollar]
- closes #2506 fix escaping of quotes on command strings [@ddollar]
=> [RELEASE] 20180228

cmd/region-options/main.go, provider/aws/formation/rack.json
- closes #2516 update ecs ami [@ddollar]
=> [RELEASE] 20180302

client/client_test.go, client/system.go, cmd/convox/uninstall.go, provider/aws/apps.go, provider/aws/formation/app.json.tmpl, provider/aws/helpers.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/aws/releases.go, provider/local/process.go, sync/sync.go
- closes #2510 fix ALB Listener Rule Priority conflict. [@ffjia]
- closes #2519 log detached processes to app logs [@ddollar]
=> [RELEASE] 20180306

cmd/region-options/main.go, docker-compose.yml, provider/aws/aws.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2527 add parameter to run timers in fargate [@ddollar]
=> [RELEASE] 20180308

cmd/build/main.go
- closes #2534 dont mark build complete until release has been created [@ddollar]
=> [RELEASE] 20180309

api/controllers/apps.go, api/controllers/helpers.go, api/controllers/system.go, provider/aws/apps.go, provider/aws/apps_test.go, provider/aws/helpers.go, provider/aws/logs.go, provider/aws/system.go, provider/aws/workers_events.go
- closes #2541 add cloudformation and ecs events to app logs [@ddollar]
=> [RELEASE] 20180310

api/controllers/builds.go, provider/aws/formation/app.json.tmpl
- closes #2544 only use cpu and memory parameters to services when using fargate [@ddollar]
- closes #2546 dont panic when build is unable to be created [@ddollar]
=> [RELEASE] 20180312

api/controllers/helpers.go, api/controllers/processes.go, cmd/convox/start.go, manifest1/run.go, provider/aws/processes.go, provider/local/event.go, provider/local/process.go, sdk/client.go, structs/process.go, sync/sync.go
- closes #2547 fixes for local file sync [@ddollar]
=> [RELEASE] 20180313

provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2549 update ecs amis [@ddollar]
- closes #2551 add param to disable internal domains [@ddollar]
=> [RELEASE] 2017031302

manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/timer.go, manifest/yaml.go, provider/aws/formation/app.json.tmpl, provider/aws/helpers.go
- closes #2554 read scale defaults from convox.yml [@ddollar]
- closes #2556 support both 5 and 6 terms in cron expressions [@ddollar]
=> [RELEASE] 20180316

cmd/convox/builds.go, cmd/convox/main.go, provider/aws/formation/rack.json, sdk/client.go
- closes #2558 add builds release command [@ddollar]
- closes #2559 update amis, efs in us-west-1 [@ddollar]
=> [RELEASE] 20180320

ci/tests/example-app, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, provider/aws/capacity.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/helpers.go, provider/aws/processes.go, provider/aws/releases.go
- closes #2564 use tags to ensure order when switching a rack private [@ddollar]
- closes #2565 default to gen2 [@ddollar]
- closes #2566 add parameter to run app services in fargate [@ddollar]
=> [RELEASE] 20180327

ci/dependencies-pre.sh, provider/aws/formation/rack.json, provider/aws/helpers.go
- closes #2568 replace underscores with dashes [@ddollar]
- closes #2569 allow custom router security group [@ddollar]
=> [RELEASE] 20180402

cmd/convox/start.go, provider/aws/formation/rack.json, provider/local/container.go
- closes #2590 use custom security group for spot instances [@ddollar]
- closes #2591 use a pseudo-tty when running local containers [@ddollar]
=> [RELEASE] 20180411

cmd/convox/deploy.go, provider/aws/builds.go, provider/aws/formation/app.json.tmpl, provider/local/service.go
- closes #2593 display correct endpoints for local rack apps [@ddollar]
- closes #2594 allow http codes 200-399 for health checks [@ddollar]
- closes #2596 AWS: Defer marking build as complete until we have release info [@thieman]
=> [RELEASE] 2018041102

api/controllers/builds.go, api/controllers/helpers.go, client/builds.go, cmd/build/main.go, cmd/convox/start.go, provider/aws/builds.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/processes.go, provider/aws/system.go, provider/aws/template.go, provider/local/build.go, provider/local/helpers.go, structs/build.go
- closes #2597 custom manifest support [@ddollar]
- closes #2599 hash listener rule priority based on app, service, domain [@ddollar]
- closes #2600 remove converging status to avoid ecs throttling [@ddollar]
- closes #2602 change default builder params [@ddollar]
=> [RELEASE] 20180415

api/controllers/builds.go, api/controllers/routes.go, cmd/convox/builds.go, cmd/convox/helpers/helpers.go, cmd/convox/start.go, provider/local/converge.go, provider/local/local.go, provider/local/process.go, sdk/build.go
- closes #2607 dont panic when matcher gets an invalid line [@ddollar]
- closes #2608 import builds via ObjectStore, avoid multipart buffering [@ddollar]
- closes #2609 volume persistence for local resources [@ddollar]
- closes #2611 persistence for local service volumes [@ddollar]
=> [RELEASE] 20180420

README.md, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/helpers.go, provider/aws/processes.go, provider/aws/template.go
- closes #2601 AWS: Account for eventual consistency in DescribeTasks [@thieman]
- closes #2612 add Rack tag to router [@ddollar]
- closes #2614 service autoscaling [@ddollar]
- closes #2615 Change Development.md to DEVELOPMENT.md [@denmat]
=> [RELEASE] 20180423

provider/aws/certificates.go, provider/aws/formation/app.json.tmpl
- closes #2617 fix error message for ssl update on gen2 [@ddollar]
- closes #2619 fix hardcoded scaling min/max [@ddollar]
=> [RELEASE] 20180425

cmd/region-options/main.go, provider/aws/formation/rack.json
- closes #2621 ami updates and new fargate regions [@ddollar]
=> [RELEASE] 20180429

manifest/service.go, provider/aws/formation/app.json.tmpl, provider/aws/helpers.go, provider/aws/processes.go, provider/aws/releases.go
- closes #2624 set proper env in one-off run [@ddollar]
- closes #2626 only set desired count on first deploy [@ddollar]
=> [RELEASE] 20180502

manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2628 configurable log retention [@ddollar]
- closes #2629 better defaults for convox init [@ddollar]
- closes #2632 add test for yaml inheritance [@ddollar]
=> [RELEASE] 20180503

cmd/convox/login.go, cmd/convox/main.go, cmd/convox/start.go
- closes #2644 dont worry about certs on local health checks [@ddollar]
- closes #2645 support direct login to older racks [@ddollar]
- closes #2647 allow partial names with --rack [@ddollar]
=> [RELEASE] 20180507

cmd/convox/login.go, cmd/convox/main.go, cmd/convox/switch.go, provider/local/container.go
- closes #2648 better handling of default scenarios after fresh login [@ddollar]
- closes #2649 only consider convox labels during container inspection [@ddollar]
=> [RELEASE] 20180508

cmd/convox/login.go, cmd/convox/rack.go, cmd/convox/switch.go
- closes #2652 better check for local racks running [@ddollar]
- closes #2653 if we log in to a host with only one remote rack, switch to it [@ddollar]
=> [RELEASE] 20180509

cmd/convox/start.go, provider/local/container.go, provider/local/converge.go, provider/local/process.go, router/rack.go, router/router.go
- closes #2677 selective start of services in gen2 [@ddollar]
- closes #2678 only converge services and resources [@ddollar]
- closes #2681 use proper rack name in resource hostname [@ddollar]
- closes #2682 make sure to get unused ip for rack base [@ddollar]
=> [RELEASE] 20180520

cmd/build/main.go, cmd/convox/main.go, cmd/convox/start.go, helpers/provider.go, manifest/build.go, manifest/environment.go, manifest/helpers.go, manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go, provider/aws/builds.go, provider/aws/processes.go, provider/aws/releases.go, provider/aws/service.go, provider/local/container.go, provider/local/system_linux.go, router/proxy.go
- closes #2688 pass through proper host header [@ddollar]
- closes #2689 fix linux install paths [@ddollar]
- closes #2690 use router dns in local rack containers [@ddollar]
- closes #2691 add shared environment section to manifest [@ddollar]
- closes #2693 better handling of the case of no local racks installed [@ddollar]
=> [RELEASE] 20180523

bin/milestone-pr, cmd/convox/uninstall.go, provider/aws/apps.go, provider/aws/formation/g1/app.json.tmpl, provider/aws/lambda/autoscale/handler.go, provider/aws/releases.go
- closes #2703 remove period uninstalling convox message [@ndbroadbent]
- closes #2707 dont autoscale width for agents [@ddollar]
- closes #2708 reduce gen1 parameter count [@ddollar]
=> [RELEASE] 20180531

cmd/region-options/main.go, manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #2706 change default stickiness duration to 15s [@ddollar]
- closes #2709 update ecs amis [@ddollar]
- closes #2712 make sure manifest environment is loaded at service level [@ddollar]
=> [RELEASE] 20180601

bin/milestone-pr, manifest/manifest.go, manifest/manifest_test.go, manifest/testdata/simple.yml
- closes #2714 avoid modification of env passed in to manifest loader [@ddollar]
=> [RELEASE] 20180603

cmd/convox/rack.go, provider/aws/lambda/autoscale/handler.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/local/system.go, router/host.go, router/rack.go, router/router.go
- closes #2718 add BUILD and BUILD_DESCRIPTION to one-off gen1 tasks [@ddollar]
- closes #2719 add lock to local router ip generation to prevent conflicts [@ddollar]
- closes #2721 better handling of service/instance paging in autoscaler [@ddollar]
- closes #2723 start local rack with the cli version [@ddollar]
=> [RELEASE] 20180606

manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go, provider/aws/formation/app.json.tmpl
- closes #2722 add service attribute to turn off load balancer stickiness [@ddollar]
=> [RELEASE] 20180608

provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json
- closes #2729 Add trailing slash to s3 log file prefix [@mwarkentin]
- closes #2731 gen1 elb access logs [@ddollar]
=> [RELEASE] 20180618

bin/gen-cert, provider/aws/formation/app.json.tmpl
- closes #2746 Use a longer password for certificate generation [@nitaigao]
- closes #2751 allow 401 to pass health check [@ddollar]
=> [RELEASE] 20180704

provider/aws/formation/rack.json
- closes #2753 prune docker images from build instance [@ddollar]
=> [RELEASE] 20180708

Gopkg.lock, cmd/convox/helpers.go, cmd/convox/racks.go, cmd/convox/run.go, cmd/convox/start.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/service.go, vendor/github.com/convox/stdcli/helpers.go, vendor/github.com/convox/stdsdk/client.go
- closes #2756 allow individual services to be placed on fargate [@ddollar]
- closes #2759 cli should work without docker or logging in [@ddollar]
- closes #2761 Double memory reservation of monitor task to 128mb [@thieman]
- closes #2762 handle non-interactive tty for convox run [@ddollar]
=> [RELEASE] 20180716

api/api.go, cmd/convox/deploy.go, cmd/convox/env.go, cmd/convox/rack.go, cmd/monitor/main.go, main.go, provider/local/system.go, provider/provider.go
- closes #2763 restore --id and --wait to deploy and env unset [@ddollar]
- closes #2765 proper error for unknown provider, fixes #2764 [@ddollar]
- closes #2766 give local rack time to start up after install [@ddollar]
=> [RELEASE] 2018071602

ci/test.sh, cmd/convox/registries.go, provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/postgres.tmpl, provider/aws/templates/resource/redis.tmpl
- closes #2771 restore registries commands to cli [@ddollar]
- closes #2772 fix version parameters for resources [@ddollar]
=> [RELEASE] 20180719

provider/aws/formation/rack.json, provider/aws/templates/resource/webhook.tmpl
- closes #2776 create webhook role under convox path [@ddollar]
- closes #2777 also prune old images from regular instances [@ddollar]
=> [RELEASE] 2017071902

Gopkg.lock, cmd/convox/helpers.go, cmd/convox/start.go, cmd/convox/switch.go, cmd/convox/version.go, provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/postgres.tmpl, provider/aws/templates/resource/redis.tmpl, vendor/github.com/convox/stdapi/router.go, vendor/github.com/convox/stdsdk/client.go
- closes #2780 use correct parameter name for resource templates [@ddollar]
- closes #2781 store rack context for multiple hosts [@ddollar]
- closes #2782 tweak websocket buffers [@ddollar]
=> [RELEASE] 20180720

cmd/convox/run.go, helpers/tar.go, provider/aws/resource.go, provider/aws/templates/resource/s3.tmpl, provider/aws/templates/resource/sns.tmpl, provider/aws/templates/resource/sqs.tmpl
- closes #2797 restore s3, sns, sqs resource types [@ddollar]
- closes #2799 allow building from symlink dirs [@ddollar]
- closes #2803 use entrypoint on attached runs [@ddollar]
=> [RELEASE] 20180725

router/host.go, router/rack.go, router/router.go
- closes #2805 prevent ip conflicts in local router [@ddollar]
=> [RELEASE] 20180728

provider/local/local.go
- closes #2809 dont error on pre-install initialization [@ddollar]
=> [RELEASE] 2018072802

cmd/convox/apps.go, convox.yml, provider/local/app.go, provider/local/release.go, router/dns_linux.go, router/helpers_linux.go
- closes #2820 app logs should follow changing processes on local rack [@ddollar]
- closes #2821 Ubuntu 18 compatibility fixes for Local rack installation. [@ectrimble20]
- closes #2822 wake apps when promoting in local rack [@ddollar]
=> [RELEASE] 20180802

provider/aws/apps.go, provider/aws/aws.go, provider/aws/certificates.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/resource/mysql.json, provider/aws/formation/service.json.tmpl, provider/aws/helpers.go, provider/aws/instances.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/aws/releases.go, provider/aws/service.go, provider/aws/system.go, provider/aws/system_test.go, provider/aws/template.go, provider/aws/workers_agent.go, provider/aws/workers_events.go
- closes #2819 move services to a nested cloudformation stack [@ddollar]
- closes #2825 add app-level mysql resource [@ddollar]
=> [RELEASE] 20180806

provider/aws/formation/resource/memcached.json, provider/aws/formation/resource/mysql.json, provider/aws/formation/resource/postgres.json, provider/aws/resource.go
- closes #2827 support legacy resources [@ddollar]
- closes #2828 embedded memcached resources [@ddollar]
=> [RELEASE] 20180809

cmd/region-options/main.go, provider/aws/apps.go, provider/aws/formation/rack.json, provider/aws/logs.go, provider/aws/system.go, provider/local/app.go, provider/local/system.go, sdk/methods.go, structs/mock_Provider.go, structs/provider.go
- closes #2831 update ecs amis [@ddollar]
- closes #2832 allow logs to close and stop polling [@ddollar]
=> [RELEASE] 20180810

cmd/convox/rack.go, provider/aws/apps.go, provider/aws/apps_test.go, provider/aws/builds_test.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/object.go, provider/aws/processes_test.go, provider/aws/releases_test.go, provider/aws/resource_test.go, provider/aws/service.go, provider/aws/system.go
- closes #2836 add links and resource env vars to timer tasks [@ddollar]
- closes #2837 allow dev racks to update with internal template [@ddollar]
- closes #2838 allow network isolation of app services [@ddollar]
- closes #2840 reduce service-level stack output count [@ddollar]
=> [RELEASE] 20180813

cmd/convox/env.go, cmd/convox/scale.go, cmd/convox/services.go, cmd/convox/ssl.go, manifest/manifest_test.go, manifest/resource.go, manifest/testdata/full.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/resource/memcached.json.tmpl, provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/formation/resource/redis.json.tmpl, provider/aws/releases.go, sdk/compat.go
- closes #2847 allow app-based resources to specify options [@ddollar]
- closes #2851 update ecs amis [@ddollar]
- closes #2852 add cli compatibility with older racks [@ddollar]
=> [RELEASE] 20180815

ci/test.sh, cmd/convox/apps.go, sdk/compat.go
- closes #2855 add compatibility for old detached run api [@ddollar]
- closes #2856 allow apps create with no arg to use current directory name [@ddollar]
- closes #2858 make ci fetch more reliable [@ddollar]
=> [RELEASE] 20180817

Gopkg.lock, cmd/convox/exec.go, cmd/convox/instances.go, cmd/convox/run.go, manifest/manifest.go, manifest/manifest_test.go, manifest/service.go, manifest/testdata/full.yml, manifest/yaml.go, provider/aws/formation/resource/redis.json.tmpl, provider/aws/formation/service.json.tmpl, provider/aws/template.go, provider/aws/workers_spotreplace.go, provider/local/converge.go, sdk/compat.go, sdk/sdk.go, vendor/github.com/convox/stdapi/context.go, vendor/github.com/convox/stdcli/context.go, vendor/github.com/convox/stdsdk/options.go
- closes #2859 use unique name for custom autoscaling target [@ddollar]
- closes #2860 update stdcli and better support for non-raw exec terminals [@ddollar]
- closes #2862 add links to services in local provider [@slaskis]
- closes #2863 add auth token and encryption to redis resource [@slaskis]
- closes #2864 allow agents to open tcp and udp ports on each host [@ddollar]
- closes #2865 re-add timeout to convox run [@ddollar]
=> [RELEASE] 20180821

provider/aws/apps.go, provider/aws/builds_test.go, provider/aws/processes_test.go, provider/aws/releases_test.go, provider/aws/service.go
- closes #2869 reduce calls to cloudformation apis [@ddollar]
=> [RELEASE] 20180823

cmd/convox/run.go
- closes #2882 process run compatibility [@ddollar]
=> [RELEASE] 20180827

.circleci/config.yml, .travis.yml, Dockerfile, cmd/build/Dockerfile, cmd/convox/rack.go, cmd/convox/registries.go, cmd/convox/scale.go, sdk/compat.go
- closes #2879 updates for go 1.11 [@ddollar]
- closes #2884 cli compatibility with older racks [@ddollar]
=> [RELEASE] 2018082702

ci/test.sh, cmd/convox/exec.go, cmd/convox/run.go, convox.yml, pkg/api/process_test.go, pkg/structs/process.go, provider/aws/processes.go
- closes #2888 detect if stdin is not a tty and pass down to docker [@ddollar]
=> [RELEASE] 20180828

Gopkg.lock, cmd/convox/builds.go, pkg/api/controllers.go, pkg/api/error.go, pkg/generate/template/controller.tmpl, provider/aws/formation/rack.json, vendor/github.com/convox/stdcli/context.go, vendor/github.com/convox/stdcli/reader.go
- closes #2890 update stdcli package for easier testing [@ddollar]
- closes #2892 internal router should use internal security group [@ddollar]
- closes #2895 remove unused ApiError type [@ddollar]
=> [RELEASE] 20180829

provider/aws/service.go
- closes #2898 handle pre-substack services [@ddollar]
=> [RELEASE] 20180901

pkg/build/build.go, pkg/build/build_test.go, pkg/cli/helpers.go, pkg/cli/login.go, pkg/cli/rack.go, pkg/cli/rack_test.go, pkg/helpers/tick.go, pkg/metrics/metrics.go, pkg/start/gen2.go, pkg/structs/system.go, provider/aws/aws.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/resource/memcached.json.tmpl, provider/aws/formation/service.json.tmpl, provider/aws/releases.go, provider/aws/system.go, provider/aws/workers_heartbeat.go, provider/local/converge.go, provider/local/local.go, provider/local/system.go, provider/local/workers.go, sdk/auth.go, sdk/compat.go
- closes #2917 add required password parameter to memcached stack [@ddollar]
- closes #2918 tweak build tag used in local rack [@ddollar]
- closes #2919 add parameter to set rack to only allow internal services [@ddollar]
- closes #2920 make start logs more robust [@ddollar]
- closes #2921 default to t3 instances [@ddollar]
- closes #2922 cli compatibility with old formation api [@ddollar]
- closes #2923 simplify metrics [@ddollar]
=> [RELEASE] 20180906

Dockerfile, pkg/cli/apps_test.go, pkg/cli/helpers.go
- closes #2934 return an error from wait if rolled back [@ddollar]
- closes #2935 change binary build order [@ddollar]
=> [RELEASE] 20180913

pkg/cli/apps_test.go, pkg/cli/deploy_test.go, pkg/cli/helpers.go, pkg/cli/rack_test.go, provider/aws/formation/service.json.tmpl
- closes #2938 add security group to service output when isolated [@ddollar]
- closes #2939 retry logs on error during wait sessions [@ddollar]
=> [RELEASE] 20180918

pkg/generate/template.go, provider/aws/docker.go, provider/aws/docker_test.go, provider/aws/formation/rack.json, provider/local/app.go, provider/local/process.go, provider/local/workers.go, sdk/methods.go
- closes #2942 Fix newline bug with Docker prune cron [@thieman]
- closes #2943 quality of life tweaks on local rack [@ddollar]
- closes #2945 ami updates [@ddollar]
=> [RELEASE] 20180920

convox.yml, provider/aws/formation/rack.json, provider/aws/helpers.go
- closes #2954 mount docker volume later so it doesn't get overloaded [@ddollar]
=> [RELEASE] 20180924

pkg/cli/fixtures_test.go, pkg/cli/releases.go, pkg/cli/releases_test.go, pkg/structs/release.go, provider/aws/processes.go, provider/aws/processes_test.go, provider/aws/releases.go, provider/local/process.go
- closes #2964 Making build description visible in releases. [@iCreateJB]
- closes #2970 fixes for launching one-off processes [@ddollar]
=> [RELEASE] 20181005

pkg/router/interface_linux.go, provider/local/system_linux.go
- closes #2972 change vlan id for linux local rack to avoid conflict [@ddollar]
=> [RELEASE] 20181007

pkg/cli/apps.go, pkg/cli/apps_test.go, pkg/structs/app.go, provider/aws/apps.go, provider/aws/resource.go, provider/aws/templates/resource/redis.tmpl, provider/aws/templates/resource/s3.tmpl, provider/local/app.go
- closes #2980 fix typo in redis resource options help docs [@btucker]
- closes #2985 encrypt s3 resources by default [@ddollar]
- closes #2986 lock and unlock apps for termination protection [@ddollar]
- closes #2987 skip password on resource updates [@ddollar]
=> [RELEASE] 20181019

pkg/cli/scale.go, provider/local/container.go
- closes #2990 fix port in local RACK_URL [@ddollar]
- closes #2991 fix help for convox scale [@ddollar]
=> [RELEASE] 20181023

Gopkg.lock, Gopkg.toml, pkg/cli/builds.go, pkg/cli/deploy_test.go, pkg/cli/releases.go, pkg/cli/releases_test.go, pkg/structs/build.go, provider/aws/builds.go, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go
- closes #2998 allow development builds from cli [@ddollar]
- closes #2999 override yaml package with alias fixes [@ddollar]
- closes #3000 release promote waits for app to be running before proceeding [@ddollar]
=> [RELEASE] 20181026

pkg/cli/auth.go, pkg/cli/engine.go, pkg/cli/helpers.go, sdk/sdk.go
- closes #3010 fetch session id at runtime [@ddollar]
=> [RELEASE] 20181105

cmd/regions/main.go, provider/aws/formation/rack.json
- closes #3014 final amazon linux 1 ecs ami update [@ddollar]
=> [RELEASE] 20181109

cmd/regions/main.go, pkg/start/gen2.go, pkg/start/gen2_test.go, pkg/start/start_test.go, provider/aws/formation/rack.json.orig, provider/aws/templates/resource/redis.tmpl
- closes #2989 use new amazon linux 2 amis [@ddollar]
- closes #3027 Update redis description - cache.t2 may now be clustered [@kochalex]
- closes #3032 reduce noise from healthchecks for convox start [@ddollar]
=> [RELEASE] 20181203

cmd/regions/main.go, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, sdk/sdk.go
- closes #3035 re-add init process and privileged. [@ffjia]
- closes #3038 trigger session creation for websocket endpoints [@ddollar]
- closes #3039 update ecs amis [@ddollar]
=> [RELEASE] 20181211

pkg/prefix/writer.go, pkg/start/gen2.go, provider/local/process.go, vendor/github.com/convox/stdcli/writer.go
- closes #3043 prevent interruption of output when stripping colors [@ddollar]
- closes #3044 handle long lines in log output [@ddollar]
=> [RELEASE] 20181213

provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl, provider/aws/processes.go
- closes #3048 add SERVICE env var to gen2 apps [@ddollar]
- closes #3049 handle changed failure reason for DescribeContainerInstances [@ddollar]
=> [RELEASE] 20181215

pkg/router/proxy.go
- closes #3051 include query string in websocket proxy [@jayjun]
=> [RELEASE] 20181217

provider/aws/builds.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/helpers.go, provider/aws/processes.go, provider/aws/system.go, provider/aws/template.go
- closes #3053 redirect http to https by default [@ddollar]
- closes #3056 support run on apps with no promoted release [@ddollar]
=> [RELEASE] 20190103

REGIONS, pkg/cli/helpers.go, pkg/cli/login.go, provider/aws/formation/rack.json
- closes #3058 support for eu-north-1 [@ddollar]
- closes #3059 make internal suffix configurable [@ddollar]
- closes #3061 urlencode rack passwords [@ddollar]
=> [RELEASE] 20190108

provider/aws/formation/rack.json, provider/aws/lambda/formation/handler/kms.go, provider/aws/processes.go
- closes #3062 switch to t3 instances by default [@ddollar]
- closes #3063 allow configuring a security group for private api access [@ddollar]
- closes #3065 restore resource link vars to one-off runs [@ddollar]
- closes #3066 enable kms annual rotation [@ddollar]
=> [RELEASE] 20190111

provider/aws/formation/rack.json
- closes #3075 allow disabling swap with SwapSize=0 [@ddollar]
=> [RELEASE] 20190121

pkg/manifest/manifest.go, provider/k8s/helpers.go, provider/k8s/process.go, provider/k8s/template.go, provider/k8s/template/service.yml.tmpl, provider/local/local.go, provider/local/resource.go, provider/local/template/resource/memcached.yml.tmpl, provider/local/template/resource/mysql.yml.tmpl, provider/local/template/resource/postgres.yml.tmpl, provider/local/template/resource/redis.yml.tmpl
- closes #3080 decrease default cpu and memory for local rack [@ddollar]
- closes #3081 restore resource apis for local rack [@ddollar]
- closes #3082 use PersistentVolumes for local volumes [@ddollar]
- closes #3083 properly configure local dns in one-off runs [@ddollar]
=> [RELEASE] 20190124

pkg/start/gen2.go, provider/aws/formation/rack.json, provider/aws/system.go
- closes #3099 handle --options to ADD/COPY [@ddollar]
- closes #3100 autoscaler needs api-level permission to cascade to stack update [@ddollar]
- closes #3102 allow AvailabilityZones to be overridden with params set [@ddollar]
=> [RELEASE] 20190128

Dockerfile, Makefile, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/timer.json.tmpl, provider/aws/releases.go
- closes #3109 separate timers into substacks [@ddollar]
- closes #3110 use on-demand dynamodb tables [@ddollar]
- closes #3113 use ubuntu as rack base image [@ddollar]
=> [RELEASE] 20190131

provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/helpers.go, provider/aws/releases.go, provider/aws/resource.go
- closes #3114 preserve resource parameter defaults [@ddollar]
=> [RELEASE] 20190205

provider/aws/formation/timer.json.tmpl
- closes #3116 use autogenerated name for timer [@ddollar]
=> [RELEASE] 20190207

provider/aws/formation/rack.json, provider/local/system_darwin.go
- closes #3118 attempt to clean up very old racks when installing new local rack [@ddollar]
- closes #3120 updating ami versions to to latest Amazon ECS-Optimized Amazon Linux … [@camerondgray]
=> [RELEASE] 20190213

provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl, provider/local/template/system.yml.tmpl
- closes #3122 dont allow k8s dns to attempt relative dns lookups in router [@ddollar]
- closes #3123 use correct export for router internal group [@ddollar]
- closes #3124 raise default ulimits for ecs services [@ddollar]
=> [RELEASE] 20190214

provider/k8s/build.go, provider/k8s/docker_darwin.go, provider/k8s/docker_linux.go, provider/k8s/docker_windows.go, provider/k8s/helpers.go, provider/k8s/k8s.go, provider/k8s/system.go, provider/k8s/template/rack.yml.tmpl
- closes #3126 handle microk8s alternate docker socket location [@ddollar]
=> [RELEASE] 20190218

pkg/router/http.go, provider/local/template/system.yml.tmpl
- closes #3128 properly forward content length in local router [@ddollar]
- closes #3129 keep local router alive during updates [@ddollar]
=> [RELEASE] 20190219

provider/k8s/helpers.go, provider/k8s/process.go, provider/k8s/release.go, provider/k8s/template.go, provider/k8s/template/service.yml.tmpl, provider/k8s/template/volumes.yml.tmpl, provider/local/system_darwin.go, provider/local/system_linux.go, provider/local/system_windows.go
- closes #3131 handle shared volumes for k8s [@ddollar]
- closes #3132 add network setup step for linux local rack [@ddollar]
=> [RELEASE] 20190221

pkg/router/ingress.go, provider/k8s/helpers.go
- closes #3135 add maximum to volume name length [@ddollar]
- closes #3136 use standard service-discovery hostname on local rack [@ddollar]
=> [RELEASE] 20190227

.circleci/config.yml, .travis.yml, Dockerfile, pkg/router/backend.go, pkg/router/backend_memory.go, pkg/router/ca.go, pkg/router/controller_ingress.go, pkg/router/dns.go, pkg/router/http.go, pkg/router/http_test.go, pkg/router/idle.go, pkg/router/router.go, provider/k8s/k8s.go, provider/k8s/service.go, provider/k8s/template.go, provider/k8s/template/rack.yml.tmpl, provider/k8s/template/router.yml.tmpl, provider/local/service.go, provider/local/system.go
- closes #3144 refactor handling of ingress domains [@ddollar]
- closes #3145 refactor local router and reduce cpu utilization [@ddollar]
=> [RELEASE] 20190302

Gopkg.lock, cmd/rack/main.go, cmd/router/main.go, pkg/api/api.go, pkg/api/api_test.go, pkg/cli/cli_test.go, pkg/router/dns.go, pkg/router/http.go, pkg/router/http_test.go, pkg/router/router.go, provider/aws/formation/rack.json, provider/local/system.go, vendor/github.com/convox/stdapi/api.go, vendor/github.com/convox/stdapi/context.go, vendor/github.com/convox/stdapi/router.go, vendor/github.com/convox/stdapi/server.go, vendor/github.com/convox/stdapi/template.go
- closes #3151 gracefully shut down http servers [@ddollar]
- closes #3153 add http redirect to internal router and make default route 404 [@ddollar]
=> [RELEASE] 20190307

pkg/router/backend.go, pkg/router/backend_kubernetes.go, pkg/router/cache_dynamo.go, pkg/router/controller_ingress.go, pkg/router/controller_pod.go, pkg/router/dns.go, pkg/router/http.go, pkg/router/router.go, pkg/router/storage.go, pkg/router/storage_dynamo.go, pkg/router/storage_memory.go, provider/k8s/template/rack.yml.tmpl, provider/k8s/template/service.yml.tmpl
- closes #3154 rework router idling logic [@ddollar]
=> [RELEASE] 20190308

cmd/regions/main.go, pkg/helpers/aws.go, provider/aws/formation/rack.json, provider/aws/system.go, provider/k8s/controller_node.go, provider/k8s/controller_pod.go, provider/k8s/k8s.go, provider/k8s/resource.go, provider/k8s/system.go, provider/k8s/template/rack.yml.tmpl, provider/k8s/template/system.yml.tmpl, provider/local/helpers.go, provider/local/log.go, provider/local/system.go
- closes #3170 tweak router scale requests [@ddollar]
- closes #3171 add service prefix to log output [@ddollar]
- closes #3173 prepare k8s provider for alternative backends [@ddollar]
- closes #3174 ecs ami update [@ddollar]
=> [RELEASE] 20190318

.travis.yml, pkg/cli/resources_test.go, provider/aws/formation/app.json.tmpl, provider/aws/templates/resource/webhook.tmpl, provider/k8s/helpers.go, provider/k8s/process.go, provider/k8s/release.go, provider/k8s/service.go, provider/k8s/template/config.yml.tmpl, provider/k8s/template/service.yml.tmpl
- closes #3190 provide rack ca certificate as a file [@ddollar]
- closes #3191 upgrade lambda handlers to use nodejs 8.10 [@ddollar]
- closes #3193 use the currently-promoted release to pull the current manifest [@ddollar]
=> [RELEASE] 20190325

pkg/router/backend.go, pkg/router/controller_ingress.go, pkg/router/http.go, pkg/router/router.go, pkg/router/storage.go, pkg/router/storage_dynamo.go, pkg/router/storage_memory.go, pkg/start/gen2.go, pkg/start/gen2_test.go, pkg/structs/release.go, provider/aws/processes.go, provider/k8s/controller.go, provider/k8s/controller_deployment.go, provider/k8s/k8s.go, provider/k8s/release.go, provider/k8s/template/ingress.yml.tmpl, provider/local/app.go
- closes #3198 prevent apps from idling when active in convox start [@ddollar]
- closes #3199 reduce cpu usage by k8s router [@ddollar]
- closes #3200 simplify deployment state changes [@ddollar]
- closes #3202 use static port for ingress protocol [@ddollar]
- closes #3203 handle new task arn format for pid [@ddollar]
=> [RELEASE] 20190328

pkg/cli/proxy_test.go, pkg/start/gen2.go, pkg/start/gen2_test.go, pkg/structs/release.go, provider/k8s/service.go
- closes #3204 allow force to bypass currently-updating checks [@ddollar]
- closes #3205 scope service installs to the service name [@ddollar]
=> [RELEASE] 20190329

pkg/helpers/aws.go, pkg/router/http.go, pkg/router/router.go, pkg/router/storage_dynamo.go, pkg/router/storage_memory.go, provider/k8s/release.go, provider/k8s/template.go, provider/k8s/template/rack.yml.tmpl, provider/k8s/template/service.yml.tmpl, provider/local/template/rack.yml.tmpl
- closes #3207 tweak router storage mechanisms [@ddollar]
- closes #3208 store env in k8s secrets [@ddollar]
=> [RELEASE] 20190404

provider/k8s/helpers.go, provider/k8s/release.go, provider/k8s/template/service.yml.tmpl
- closes #3214 fix handling of env defaults in k8s provider [@ddollar]
=> [RELEASE] 20190411

Makefile, cmd/convox/Makefile, provider/aws/Makefile, provider/aws/formation/rack.json, provider/aws/lambda/autoscale/Makefile, provider/aws/lambda/formation/Makefile, provider/aws/lambda/lifecycle/Makefile, provider/aws/lambda/syslog/Makefile, provider/k8s/app.go
- closes #3217 prevent reserved app names on k8s [@ddollar]
- closes #3218 allow switching rack router to main alb [@ddollar]
- closes #3220 clean up release process [@ddollar]
=> [RELEASE] 20190415

Gopkg.lock, pkg/helpers/time.go, provider/aws/apps.go, provider/aws/apps_test.go, provider/aws/certificates.go, provider/aws/helpers.go, provider/aws/instances.go, provider/aws/releases.go, provider/aws/resource.go, provider/aws/service.go, provider/aws/system.go, provider/aws/workers_events.go, vendor/github.com/convox/stdsdk/client.go
- closes #3225 use lowercase origin for hostname matching [@ddollar]
- closes #3226 make release promotion events more resilient [@ddollar]
=> [RELEASE] 20190430

.circleci/config.yml, ci/deploy.sh, ci/update.sh, scripts/ci-cleanup
- closes #3239 update staging rack and apps automatically during ci [@ddollar]
=> [RELEASE] 20190505

pkg/build/docker.go, provider/k8s/process.go
- closes #3241 display output on docker errors during build [@ddollar]
- closes #3242 dynamic terminal size for k8s exec [@ddollar]
=> [RELEASE] 20190506

.circleci/config.yml, Dockerfile, Makefile, ci/dependencies.sh, provider/aws/certificates.go
- closes #3244 update internal docker version and include tests [@ddollar]
- closes #3245 prevent race during certificate deletion [@ddollar]
=> [RELEASE] 2019050602

provider/k8s/docker_darwin.go, provider/k8s/docker_linux.go, provider/k8s/docker_windows.go, provider/local/local.go
- closes #3247 propagate custom docker socket down to k8s provider [@ddollar]
=> [RELEASE] 20190508

pkg/router/backend_kubernetes.go, pkg/router/controller_deployment.go
- closes #3254 pull idle state from cache in local router [@ddollar]
=> [RELEASE] 20190522

provider/aws/formation/rack.json, provider/aws/releases.go
- closes #3256 add hostname for host gateway [@ddollar]
- closes #3257 prevent use of expired certificates for hostname matching during release [@ddollar]
=> [RELEASE] 20190528

pkg/cli/helpers.go, pkg/cli/rack.go, pkg/cli/rack_test.go, pkg/cli/racks_test.go, pkg/cli/start_test.go, pkg/cli/version_test.go, provider/local/system.go, provider/local/system_linux.go
- closes #3260 fix install order on fresh linux box [@ddollar]
=> [RELEASE] 20190605

pkg/router/backend.go, pkg/router/backend_kubernetes.go, pkg/router/dns.go, pkg/router/dns_test.go, pkg/router/router.go, provider/kaws/system.go, provider/local/template/resource/postgres.yml.tmpl, provider/local/template/system/registry.yml.tmpl, provider/local/template/system/router.yml.tmpl, scripts/create-milestone, scripts/milestone-pr
- closes #3268 force internal registry to resolve with internal cluster ip [@ddollar]
- closes #3269 use sslmode=disable for postgres on local rack [@ddollar]
=> [RELEASE] 20190624

pkg/router/dns.go, provider/local/local.go, provider/local/system.go, provider/local/template/config.yml.tmpl
- closes #3276 use 0.0.0.0 for registry ip on macos [@ddollar]
=> [RELEASE] 20190703

provider/aws/formation/rack.json
- closes #3279 use private subnets when applicable for internal router [@ddollar]
=> [RELEASE] 20190708

provider/aws/formation/rack.json
- closes #3283 only use volume target tags if region supports efs [@ddollar]
=> [RELEASE] 20190729

pkg/helpers/aws.go, provider/aws/apps_test.go
- closes #3310 scope FilterLogEvents to relevant log streams [@ddollar]
=> [RELEASE] 20191008

.circleci/config.yml, ci/test.sh, pkg/cli/apps.go, pkg/cli/apps_test.go, pkg/cli/fixtures_test.go, pkg/helpers/aws.go, pkg/helpers/provider.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/invalid.3.yml, pkg/start/gen2.go, provider/aws/apps_test.go, provider/aws/lambda/formation/handler/kms.go, provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/postgres.tmpl
- closes #3324 dont allow resources with blank types [@ddollar]
- closes #3325 clean up kms keys [@ddollar]
- closes #3326 add --wait to convox apps cancel [@ddollar]
- closes #3331 check creation and first event time for filtering log streams [@ddollar]
- closes #3332 increase ci timeout because cloudformation is slow [@ddollar]
=> [RELEASE] 20191108

provider/aws/metrics.go
- closes #3335 refine app and service level metrics [@ddollar]
=> [RELEASE] 20191114

pkg/api/api.go, provider/aws/builds.go, provider/k8s/build.go
- closes #3321 Prefix with https:// for succesful pulling of private images [@beastawakens]
=> [RELEASE] 20191118

provider/aws/builds.go
- closes #3342 Protocol safety for AWS racks too [@beastawakens]
=> [RELEASE] 20191120

provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/instances.go, provider/aws/templates/resource/webhook.tmpl, provider/kaws/formation/rack.yml
- closes #3345 Update instances.go [@martin-schibsted]
- closes #3347 Upgrading to Node 10 again [@beastawakens]
=> [RELEASE] 20191211

provider/aws/formation/g1/app.json.tmpl
- closes #3350 Fix typo in nodejs runtime [@ryanwilsonperkin]
=> [RELEASE] 20191212

provider/aws/formation/rack.json, provider/aws/lambda/formation/handler/aws.go
- closes #3349 add more backoff retries to ecs operations in custom handler [@ddollar]
- closes #3352 Rack param: ImagePullBehavior [@mattbriancon]
=> [RELEASE] 20191216

provider/aws/helpers.go, provider/k8s/helpers.go
- closes #3354 Adding in required volume for Twistlock Console [@beastawakens]
=> [RELEASE] 20200110

provider/aws/formation/timer.json.tmpl, provider/aws/releases.go
- closes #3358 BUILD env var in timers [@mattbriancon]
=> [RELEASE] 20200129

provider/aws/aws.go, provider/aws/formation/rack.json, provider/aws/registries.go
- closes #3361 Disable auth for external registries when PrivateBuild is enabled [@beastawakens]
=> [RELEASE] 20200224

provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl
- closes #3365 Allow major version upgrade and switch to default parameter groups [@beastawakens]
=> [RELEASE] 20200226

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/service.go, pkg/manifest/testdata/full.yml, provider/aws/releases.go
- closes #3368 add manual control over deployments [@ddollar]
=> [RELEASE] 20200402

cmd/convox-env/main.go, provider/aws/formation/rack.json
- closes #3367 Filter invalid headers in ALB [@rabidaudio]
- closes #3370 merge env instead of just appending [@ddollar]
- closes #3371 [RELEASE] 20200415 [@beastawakens]
=> [RELEASE] 20200415

provider/aws/templates/resource/mysql.tmpl
- closes #3372 Adding DBSnapshot option for MySQL [@beastawakens]
=> [RELEASE] 20200417

provider/aws/lambda/autoscale/handler.go
- closes #3374 Enable configuration of logging within the InstancesAutoscaler [@beastawakens]
=> [RELEASE] 20200427

pkg/manifest/manifest_test.go, pkg/manifest/service.go, pkg/manifest/testdata/full.yml, pkg/manifest/yaml.go, provider/aws/processes.go, provider/k8s/process.go
- closes #3384 support array format for service command [@ddollar]
=> [RELEASE] 20200715

provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl
- closes #3386 use new command format in templates [@ddollar]
=> [RELEASE] 20200717

pkg/cli/update.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/resource/mariadb.json.tmpl, provider/local/template/resource/mariadb.yml.tmpl
- closes #3391 Enable vulnerability scanning on ECR images [@beastawakens]
- closes #3392 Adding RouterMitigationMode param for Load Balancer [@beastawakens]
- closes #3393 cli: Make noop update checks faster [@beastawakens]
- closes #3394 Resource mariadb support [@beastawakens]
=> [RELEASE] 20200827

provider/k8s/template/app/service.yml.tmpl
- closes #3400 support new command format in local rack [@ddollar]
=> [RELEASE] 20200922

provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl
- closes #3402 Add process type labels for services and timers [@beastawakens]
=> [RELEASE] 20200930

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/service.go, pkg/manifest/testdata/full.yml, provider/aws/formation/service.json.tmpl, provider/k8s/template/app/service.yml.tmpl
- closes #3405 Mapping Termination/Grace to StopTimeout [@beastawakens]
=> [RELEASE] 20201012

provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl
- closes #3411 Ability to specify slow start duration [@beastawakens]
=> [RELEASE] 20201022

provider/aws/releases.go
- closes #3413 Pull custom Rack tags down to the App stack [@beastawakens]
=> [RELEASE] 20201028

provider/aws/formation/service.json.tmpl
- closes #3432 rack: apply cooldown param [@beastawakens]
=> [RELEASE] 20210202

provider/aws/formation/service.json.tmpl
- closes #3434 Proper scoping for cooldown in custom metric [@beastawakens]
=> [RELEASE] 20210208

pkg/cli/run.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/templates/resource/webhook.tmpl, provider/kaws/formation/rack.yml
- closes #3448 cli: add entrypoint flag to allow it to be disabled [@beastawakens]
- closes #3449 Upgrade to nodejs12.x [@beastawakens]
=> [RELEASE] 20210317

provider/aws/helpers.go, provider/k8s/helpers.go
- closes #3451 Mounting /sys/kernel/debug/ for datadog [@beastawakens]
=> [RELEASE] 20210319

provider/aws/formation/rack.json
- closes #3456 rack: Adding in Load Balancer Idle Timeout param [@beastawakens]
=> [RELEASE] 20210616

provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/postgres.tmpl
This reverts commit 7156d439befd49feb0d1d6502d033633440a42d7.
=> Revert "update Rack resource storage minimums"

pkg/cli/rack.go, provider/aws/formation/rack.json, provider/aws/helpers.go
=> Revert "User can set a schedule to shut down and up the cluster"

pkg/cli/rack.go, provider/aws/formation/rack.json
- closes #3485 Add support to schedule the rack to shutdown and up [@Twsouza]
=> [RELEASE] 20211220

provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl
- closes #3493 Adds an app param to configure health check success codes [@beastawakens]
=> [RELEASE] 20220204

provider/aws/formation/rack.json
- closes #3495 Catching some edge cases around high availability [@beastawakens]
=> [RELEASE] 20220207

.gitignore, cmd/convox/Makefile
- closes #3498 Build the binary as statically linked [@Twsouza]
=> [RELEASE] 20220214

Dockerfile
- closes #3505 Enable docker BuildKit features at the Dockerfile level [@heronrs]
=> [RELEASE] 20220303

provider/aws/formation/rack.json, provider/aws/processes.go, provider/aws/processes_test.go
- closes #3506 Get all processes and stop task from build instance [@Twsouza]
- closes #3510 Fix HttpProxy param [@Twsouza]
=> [RELEASE] 20220309

.circleci/config.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json
- closes #3504 Add s3 SSL only policy and assign lambdas to the rack VPC [@heronrs]
=> [RELEASE] 20220310

provider/aws/aws.go, provider/aws/formation/rack.json, provider/aws/workers_spotreplace.go
- closes #3513 Spot Instances and HA false should have one Instances [@Twsouza]
=> [RELEASE] 20220316

provider/aws/formation/rack.json
- closes #3515 Attach VPC to lambda refactor [@heronrs]
=> [RELEASE] 20220328

provider/aws/formation/rack.json
- closes #3517 Explicitly declare dependencies for the KMS Custom resource [@heronrs]
=> [RELEASE] 20220331

provider/aws/lambda/formation/handler/aws.go
- closes #3521 Increase max retries when creating/deleting CF KMS custom resource [@heronrs]
=> [RELEASE] 20220406

pkg/cli/apps.go, pkg/cli/apps_test.go, pkg/cli/fixtures_test.go
- closes #3523 When canceling an app update, rewrite the last active release on top [@heronrs]
=> [RELEASE] 20220412

provider/aws/formation/rack.json
- closes #3525 Consider custom VPCs in VPC Endpoints CF resources [@heronrs]
=> [RELEASE] 20220418

provider/aws/formation/rack.json
- closes #3527 Consider custom Instance Security Groups in VPC Endpoints CF resources [@fk-currenxie]
- closes #3528 Enable custom security groups for build instances [@fk-currenxie]
=> [RELEASE] 20220425

provider/aws/formation/rack.json
- closes #3530 Change minimum healthy percent for no-ha [@Twsouza]
=> [RELEASE] 20220426

pkg/api/object_test.go, pkg/structs/object.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/helpers.go, provider/aws/object.go, provider/aws/releases.go, provider/kaws/object.go
- closes #3532 Block public access to all buckets [@heronrs]
=> [RELEASE] 20220427

.circleci/config.yml, scripts/ci-cleanup
- closes #3536 Add e2e tests for installing in existing VPCs [@heronrs]
=> [RELEASE] 20220502

.gitignore, provider/aws/formation/rack.json, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/lambda/autoscale/handler.go, provider/aws/lambda/formation/handler/aws.go, provider/aws/lambda/formation/handler/formation.go, provider/aws/lambda/formation/handler/kms.go, provider/aws/lambda/lifecycle/main.go, provider/aws/templates/resource/postgres.tmpl
- closes #3541 Don't create VPC endpoint if exist [@Twsouza]
=> [RELEASE] 20220607

pkg/cli/rack.go, pkg/mock/sdk/interface.go, pkg/structs/mock_Provider.go, pkg/structs/provider.go, provider/aws/formation/rack.json, provider/aws/system.go, provider/base/system.go, provider/k8s/system.go, provider/kaws/system.go, provider/local/system.go, sdk/methods.go
- closes #3544 Add rack sync cli command [@heronrs]
- closes #3545 Add param to customize ApiMonitor memory [@Twsouza]
=> [RELEASE] 20220622

provider/aws/apps.go, provider/aws/aws.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/releases.go
- closes #3548 Use Customer Managed Key to default encrypt S3 buckets [@Twsouza]
=> [RELEASE] 20220706

pkg/cli/rack.go, provider/aws/apps.go, provider/aws/aws.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl, provider/aws/metrics.go, provider/aws/processes.go, provider/aws/releases.go
- closes #3563 Using LogDriver to send logs to CloudWatch, Syslog or disable it [@Twsouza]
- closes #3564 Do not fetch metrics if services don't have any process [@Twsouza]
=> [RELEASE] 20220816

provider/aws/formation/app.json.tmpl
- closes #3566 Fixing syslog json syntax on Timers [@Twsouza]
=> [RELEASE] 20220817

pkg/api/process_test.go, pkg/api/service_test.go, pkg/cache/cache_test.go, pkg/cli/apps_test.go, pkg/manifest1/docker_test.go, pkg/manifest1/exec_test.go, pkg/metrics/metrics_test.go, pkg/prefix/writer_test.go
Some test I added to improve coverage when i was working on this ticket: https://github.com/convox/issues-private/issues/579
=> Add unit tests for some packages

sdk/auth_test.go, sdk/compact_test.go, sdk/methods_test.go
https://github.com/convox/issues-private/issues/595
=> feat-595: Add unit test for sdk package

pkg/generate/method_test.go, pkg/sync/docker_test.go, pkg/sync/sync_test.go, pkg/token/token_test.go
https://github.com/convox/issues-private/issues/597
https://github.com/convox/issues-private/issues/599
For atom didn't add any test because it's only used in k8s
=> Add unit tests for generate, sync and toke pkg

.github/pull_request_template.md, ci/test.sh, examples/httpd/convox.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/resource/mariadb.json.tmpl, provider/aws/formation/resource/memcached.json.tmpl, provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/formation/resource/redis.json.tmpl, provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl
- closes #3594 Add additional env var for resources [@Twsouza]
- closes #3595 Add template to new Pull Requests [@Twsouza]
=> [RELEASE] 20221011

pkg/structs/build.go, provider/aws/builds.go, provider/aws/builds_test.go, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/lambda/autoscale/handler.go, provider/aws/releases.go, sdk/methods_test.go
- closes #3597 DesiredCapacity cannot be 0 or negative [@Twsouza]
- closes #3598 Feat 651 wildcard domain [@nightfury1204]
- closes #3599 Include the Spot instances when creating the schedule rack option [@Twsouza]
=> [RELEASE] 20221026

provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/templates/resource/webhook.tmpl, provider/kaws/formation/rack.yml
- closes #3601 Feat-630: Upgrade AWS lambda nodejs version to nodejs16.x [@nightfury1204]
=> [RELEASE] 20221028

provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl
- closes #3603 feat-689: Add grpc support [@nightfury1204]
=> [RELEASE] 20221107

.circleci/config.yml, provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/lambda/autoscale/handler.go, provider/aws/lambda/formation/handler/aws.go, provider/aws/lambda/lifecycle/main.go
- closes #3607 Delete VPC endpoints and remove lambda from VPC [@Twsouza]
=> [RELEASE] 20221124

.circleci/config.yml, provider/aws/formation/rack.json
- closes #3611 Recreate SubnetPrivates in the racks [@Twsouza]
=> [RELEASE] 20221202

cmd/convox/main.go, pkg/cli/rack.go, pkg/helpers/aws.go
- closes #3615 Change the cli default directory to avoid conflict with v3 cli [@nightfury1204]
- closes #3617 Fix rack sync name flag [@Twsouza]
=> [RELEASE] 20221207

provider/aws/system.go
- closes #3618 (Uninstalling V2 Racks Issue) Remove manually Stucked ECS Services before trigger the CF stack deletion [@yuriadams]
=> [RELEASE] 20221210

pkg/cli/resources.go
- closes #3620 Append scheme to the URL to parse correctly [@Twsouza]
=> [RELEASE] 20221213

provider/aws/aws.go, provider/aws/formation/rack.json, provider/aws/system.go, provider/aws/workers_events.go
- closes #3623 feat-619: Add support to add custom tags [@nightfury1204]
- closes #3624 Worker monitor should not get LogGroup from Rack API service [@Twsouza]
=> [RELEASE] 20221216

provider/aws/formation/rack.json
- closes #3645 Restrict ApiPolicy acess  [@Twsouza]
=> [RELEASE] 20230228

.gitignore, pkg/cli/rack.go, pkg/structs/system.go, provider/aws/formation/rack.json, sdk/methods.go
- closes #3647 Install cloudwatch agent on ec2 instances [@yuriadams]
- closes #3652 Add cli for attaching runtime integrations [@nightfury1204]
- closes #3654 Use SSM Parameter store to keep the API Password on task definition [@Twsouza]
=> [RELEASE] 20230321

ci/downgrade.sh, ci/install.sh, ci/update.sh, provider/aws/formation/app.json.tmpl, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/templates/resource/mysql.tmpl, provider/aws/templates/resource/s3.tmpl
- closes #3665 Add bucket OwnershipControls [@nightfury1204]
- closes #3666 Fix ci [@nightfury1204]
- closes #3667 Create new Api Policy with the missing permissions [@Twsouza]
=> [RELEASE] 20230425

provider/aws/formation/rack.json, provider/aws/telemetry.go, provider/aws/workers_heartbeat.go
- closes #3668 Store rack install & rack update telemetry data (V2) [@yuriadams]
=> [RELEASE] 20230510

ci/downgrade.sh, provider/aws/formation/rack.json, provider/aws/lambda/formation/handler/formation.go, provider/aws/lambda/formation/handler/sg_ingress.go
- closes #3683 Reimplement whitelisting for rack api [@nightfury1204]
- closes #3685 Fix Spot instances preventing rack from updating [@Twsouza]
=> [RELEASE] 20230619155345

provider/aws/formation/rack.json
- closes #3690 Enable sqs managed sse [@nightfury1204]
=> [RELEASE] 20230717202158

provider/aws/formation/rack.json, provider/aws/lambda/formation/handler/aws.go, provider/aws/lambda/formation/handler/sg_ingress.go, provider/aws/lambda/formation/handler/sg_ingress_test.go
- closes #3694 Add security group and nat ips for private build cluster to whitelist feature [@nightfury1204]
=> [RELEASE] 20230828164648

provider/aws/formation/rack.json
https://app.asana.com/0/1203637156732418/1205731221438804/f
** Any screenshot or video capture using the feature **
** Describe the changes and if it has any breaking changes in any feature **
** Describe how to test or use the feature **
=> Remove path from iam resource since aws change it's policy

Makefile, provider/aws/formation/g1/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/resource/mariadb.json.tmpl, provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/instances.go, provider/aws/instances_test.go, provider/aws/lambda/autoscale/Makefile, provider/aws/lambda/formation/data/role-policy.json, provider/aws/lambda/lifecycle/Makefile, provider/aws/lambda/syslog/Makefile, provider/aws/templates/resource/syslog.tmpl
** Any screenshot or video capture using the feature **
** Describe the changes and if it has any breaking changes in any feature **
** Describe how to test or use the feature **
=> 20231120125953

provider/aws/formation/rack.json
** Describe the task and what is the goal for it. **
** Describe the bug and the solution. **
** Any additional information **
** Any screenshot or video capture using the feature **
** Describe the changes and if it has any breaking changes in any feature **
** Describe how to test or use the feature **
=> Add new line to the user data scripts

provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/resource/mariadb.json.tmpl, provider/aws/formation/resource/mysql.json.tmpl, provider/aws/formation/resource/postgres.json.tmpl, provider/aws/releases.go
- closes #3716 Add option to put convox lambda's in vpc if rack is private for security requirements [@nightfury1204]
- closes #3717 Reorder userdata scripts [@nightfury1204]
- closes #3718 Add option for RDS parameter group name [@nightfury1204]
=> [RELEASE] 20240205115824

provider/aws/formation/app.json.tmpl, provider/aws/formation/rack.json, provider/aws/formation/service.json.tmpl, provider/aws/formation/timer.json.tmpl, provider/aws/releases.go
- closes #3723 Add support to enable encryption on shared volume efs [@nightfury1204]
- closes #3724 Add support to configure docker image prune [@nightfury1204]
- closes #3726 Add option to enable readonly root fs for ecs [@nightfury1204]
- closes #3725 Dynamodb deletion protection and point in recovery for security [@nightfury1204]
=> [RELEASE] 20240326194210

pkg/helpers/tar.go
** Describe the task and what is the goal for it. **
** Describe the bug and the solution. **
** Any additional information **
** Any screenshot or video capture using the feature **
** Describe the changes and if it has any breaking changes in any feature **
** Describe how to test or use the feature **
=> fix: close file

pkg/cli/apps.go, provider/aws/formation/app.json.tmpl, provider/aws/formation/service.json.tmpl
- closes #3736 Removed app specific unique params when importing/exporting to avoid error [@numcys]
- closes #3737 Add app param to ignore manual replica count scaling [@nightfury1204]
=> [RELEASE] 20240808200519

provider/aws/formation/rack.json
=> Revert "added rack param ecs_container_stop_timeout"

provider/aws/processes.go
Fix for convox run supporting different service names with policies support.
=> Fix/run policy add - support different service names 

provider/aws/templates/resource/redis.tmpl
Eliminates extraneous comma to maintain consistent syntax
=> Removes trailing comma in engine version default
